### ISSUE TITLE
Rasterio package looking for out of date library file

### ISSUE THREAD

**Issue by johnson-geo** [matthiasdemuzere/w2w#10]
After setting up the conda environment and attempting `python w2w.py -h`, the script crashes in the rioxarray routine within rasterio 1.2.4. 

> ImportError: libnsl.so.1: cannot open shared object file: No such file or directory

The computing cluster at my institution was recently upgraded from CentOS 7 to CentOS 8 and libnsl.so.1 is outdated; libnsl.so.2 is now the default. I have attempted to install rasterio 1.2.8 in hopes it has updated library dependencies but conda is having difficulty resolving the new environment.

**Comment by theendlessriver13** [comment]
Hi,
I can reproduce this with this dockerfile:
```dockerfile
FROM centos:8

RUN \
    yum install wget -y && \
    yum install bzip2 -y && \
    yum install unzip -y

RUN \
    wget -q https://repo.anaconda.com/miniconda/Miniconda3-py38_4.10.3-Linux-x86_64.sh && \
    bash /Miniconda3-py38_4.10.3-Linux-x86_64.sh -b

RUN \
    wget https://github.com/matthiasdemuzere/w2w/archive/refs/heads/main.zip && \
    unzip main.zip

RUN /root/miniconda3/bin/conda env create -f /w2w-main/w2w.yml
```
by running
```bash'
docker build -t test - < dockerfile
docker run test /root/miniconda3/envs/w2w/bin/python /w2w-main/w2w.py --help
```
the complete stacktrace is:
```python
Traceback (most recent call last):
  File "/w2w-main/w2w.py", line 4, in <module>
    import rioxarray
  File "/root/miniconda3/envs/w2w/lib/python3.8/site-packages/rioxarray/__init__.py", line 6, in <module>
    import rioxarray.raster_array  # noqa
  File "/root/miniconda3/envs/w2w/lib/python3.8/site-packages/rioxarray/raster_array.py", line 18, in <module>
    import rasterio
  File "/root/miniconda3/envs/w2w/lib/python3.8/site-packages/rasterio/__init__.py", line 9, in <module>
    from rasterio._base import gdal_version
ImportError: libnsl.so.1: cannot open shared object file: No such file or directory
```

It looks like `rasterio` does not link agains `libnsl` itself, but `libgdal` does and a few others in this environment as well, which may not be related to this. The issue is in the centos 8 distro itself. You can fix this by manually installing `libnsl` with 
```bash
yum install libnsl
```
This will install `libnsl.so.2`, but it is downwards compatible

Afterwards it is linked properly:
```
[root@267d33441e36 lib]# ldd libgdal.so | grep libnsl
	libnsl.so.1 => /lib64/libnsl.so.1 (0x00007f25e5c9d000)
```
And you should be able to run the tool I am not sure how conda works behind the scenes, but I am sure you need to at least recreate the environment

**Comment by johnson-geo** [comment]
Thank you for investigating this. I do not have superuser permissions on my computing cluster. Therefore, I am unable to confirm the above method on my end. I initially considered modifying the .yml file, but there were too many conflicts based on what you mentioned above.

However, I was able to find a workaround since `libnsl.so.2` is installed in Centos 8. It effectively softlinks any calls to `libnsl.so.1` to the upgraded library. I should also mention that my environment requires me to load Anaconda 3.8 in the slurm script. The process below yielded success.

> mkdir /home/${USER}/myLocalSymlinks  # this is just a directory in your home directory to hold symlinks
> ln -sf /usr/lib64/libnsl.so.2 /home/${USER}/myLocalSymlinks/libnsl.so.1 # The target depends on where `libnsl.so.2` is installed on your system

The code below are included in a slurm script. When excluding the bash init, the process also worked from the command line.
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/myLocalSymlinks  
> eval "$(conda shell.bash hook)"
> conda activate /home/${USER}/.conda/envs/w2w 
> python w2w.py -h

**Comment by matthiasdemuzere** [comment]
Sounds good @johnson-geo. Thanks for sharing your solution!
