### ISSUE TITLE
W2W hangs in wrf_remove_urban newluf for loop

### ISSUE THREAD

**Issue by lpilz** [matthiasdemuzere/w2w#100]
### Describe your issue

When modifying the `geo_em` files of my domains, using W2W with a clipped `tif` of the global LCZ dataset on domains 2 and 3 works, however using it on domain 1 causes the program to stall in the `newluf` for loop.

https://github.com/matthiasdemuzere/w2w/blob/67eeb8d70acbd6ea50b98c8119a7d3dd2da27f1e/w2w/w2w.py#L525-L530

I am using a modified W2W version (#99), but this should probably not affect this issue. I think my problem is similar to #3, however I didn't want to bump an old issue.

[geo_em.d01.nc.gz](https://github.com/matthiasdemuzere/w2w/files/9922879/geo_em.d01.nc.gz)
[geo_em.d02.nc.gz](https://github.com/matthiasdemuzere/w2w/files/9924113/geo_em.d02.nc.gz)
[geo_em.d03.nc.gz](https://github.com/matthiasdemuzere/w2w/files/9924115/geo_em.d03.nc.gz)

### w2w --version

w2w 0.4.2 (+USGS modifications)

### nc-config --all

```console
This netCDF 4.8.1 has been built with the following features: 

  --cc            -> /sw/spack-levante/openmpi-4.1.2-beqrxf/bin/mpicc
  --cflags        -> -I/sw/spack-levante/netcdf-c-4.8.1-vbnli5/include -I/usr/include -I/sw/spack-levante/hdf5-1.12.1-ddjui3/include -I/sw/spack-levante/parallel-netcdf-1.12.2-nxiert/include -I/sw/spack-levante/hdf-4.2.15-gncyvn/include
  --libs          -> -L/sw/spack-levante/netcdf-c-4.8.1-vbnli5/lib -lnetcdf
  --static        -> -lpnetcdf -ljpeg -lmfhdf -ldf -ljpeg -lhdf5_hl -lhdf5 -lm -ldl -lz -lcurl -ljpeg -lsz -ltirpc

  --has-c++       -> no
  --cxx           -> 

  --has-c++4      -> no
  --cxx4          -> 

  --has-fortran   -> no
  --has-dap       -> yes
  --has-dap2      -> yes
  --has-dap4      -> yes
  --has-nc2       -> yes
  --has-nc4       -> yes
  --has-hdf5      -> yes
  --has-hdf4      -> yes
  --has-logging   -> no
  --has-pnetcdf   -> yes
  --has-szlib     -> yes
  --has-cdf5      -> yes
  --has-parallel4 -> yes
  --has-parallel  -> yes
  --has-nczarr    -> yes

  --prefix        -> /sw/spack-levante/netcdf-c-4.8.1-vbnli5
  --includedir    -> /sw/spack-levante/netcdf-c-4.8.1-vbnli5/include
  --libdir        -> /sw/spack-levante/netcdf-c-4.8.1-vbnli5/lib
  --version       -> netCDF 4.8.1
```

### Installed Packages

```console
affine==2.3.1                                                                           
attrs==22.1.0    
brotlipy @ file:///home/conda/feedstock_root/build_artifacts/brotlipy_1648854167867/work
cdsapi @ file:///home/conda/feedstock_root/build_artifacts/cdsapi_1612970655952/work
certifi==2022.9.24
cffi @ file:///home/conda/feedstock_root/build_artifacts/cffi_1656782834004/work  
cftime==1.6.2
charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1661170624537/work
click @ file:///home/conda/feedstock_root/build_artifacts/click_1651215151197/work
click-plugins==1.1.1                                                                                                                                                                          
cligj==0.7.2                                                                                
cloudpickle==2.2.0
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1655412516417/work   
cryptography @ file:///home/conda/feedstock_root/build_artifacts/cryptography_1657173997940/work
dask==2022.9.1                                                                  
distlib @ file:///home/conda/feedstock_root/build_artifacts/distlib_1657828092311/work                                                                                                        
donfig==0.7.0
ecmwflibs==0.4.17
f90nml @ file:///home/conda/feedstock_root/build_artifacts/f90nml_1657796865258/work
filelock @ file:///home/conda/feedstock_root/build_artifacts/filelock_1660129891014/work
findlibs==0.0.2
flock==0.1
fsspec==2022.8.2
h5netcdf==1.0.2
h5py==3.7.0
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1663625384323/work
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1666781969417/work
locket==1.0.0
loguru @ file:///home/conda/feedstock_root/build_artifacts/loguru_1649442902864/work
netCDF4==1.6.1
numpy==1.23.3
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1637239678211/work
pandas==1.5.0
partd==1.3.0
platformdirs @ file:///home/conda/feedstock_root/build_artifacts/platformdirs_1657729053205/work
pluggy @ file:///home/conda/feedstock_root/build_artifacts/pluggy_1667232663820/work
py @ file:///home/conda/feedstock_root/build_artifacts/py_1636301881863/work
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1663846997386/work
pyparsing @ file:///home/conda/feedstock_root/build_artifacts/pyparsing_1652235407899/work
pyproj==3.4.0
PySocks @ file:///home/conda/feedstock_root/build_artifacts/pysocks_1661604839144/work
python-dateutil==2.8.2
pytz==2022.2.1
PyYAML==6.0
rasterio==1.3.3
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1661872987712/work
rioxarray==0.12.2
scipy==1.9.3
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
snuggs==1.4.7
tomli @ file:///home/conda/feedstock_root/build_artifacts/tomli_1644342247877/work
toolz==0.12.0
tox @ file:///home/conda/feedstock_root/build_artifacts/tox_1666792729278/work
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1662214488106/work
urllib3 @ file:///home/b/b381219/.cache/pypoetry/artifacts/01/67/f2/ecf92c52cfdc6b9ccfbcc95351b5c2708889d7031a05bc0c2a2391c5be/urllib3-1.26.12-py2.py3-none-any.whl
virtualenv @ file:///home/conda/feedstock_root/build_artifacts/virtualenv_1666787595089/work
w2w==0.4.2
wps-xr @ file:///home/b/b381219/software/projects/wps_xr/dist/wps_xr-0.1.0-py3-none-any.whl
xarray==2022.6.0
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1666647772197/work
```

**Comment by lpilz** [comment]
Hey @dargueso, thanks for offering to look into this issue. Have you had any time to give it a look yet?

**Comment by dargueso** [comment]
Hi @lpilz, Sorry, I didn't have time, I hope I can look at this tomorrow. If not, I'd have to leave it for Friday because I'm travelling. Can you send me the tif you clipped, just in case I need it to reproduce the stalling. Thanks!

**Comment by dargueso** [comment]
Hi @lpilz, sorry for the delay. I'm overloaded this week and I'm not sure when I will have the time to look at this. I will do it as soon as possible, but cannot commit to a date at the moment.

**Comment by lpilz** [comment]
Hi @dargueso, thanks for letting me know. I'll try to debug it myself, but I desperately need this data for a publication in December. Do you have any ideas on where to look for the problem? Thanks!

**Comment by dargueso** [comment]
Hi @lpilz, I have checked the code with your files and I didn't manage to make it finish yet. It takes long on the step "Create LCZ-based geo_em file", I guess because the tif files is very large, I'm still trying on a bigger computer. But it does go through the "Replace WRF urban LC with surrounding natural LC" and generates the geo_em.d0?_NoUrban.nc file without urban areas for all three domains. So your issue must be due to something else and definitely not related to #3.  Let me see if it finishes and will let you know how it goes. If it finishes successfully, I can send you the outcome files while we figure out the problem.

**Comment by matthiasdemuzere** [comment]
Hi both,

Thanks for working on this.

As I was curious, I just tested this _add_usgs implementation on a high-memory machine.
When applied on domain 03, all worked for me.

```
w2w /home/demuzmp4/data/w2w/issue100 lcz_filter_v1_clipped_c.tif geo_em.d03.nc
--> Set data, arguments and files 
> Using layer 0 of the LCZ GeoTIFF. Can be changed with -l (--lcz-band)
--> Check LCZ integrity, in terms of class labels, projection and extent
> LCZ labels as expected (1 to 17)
> LCZ provided as WGS84 (EPSG:4326)
> LCZ domain is covering WRF domain
--> Replace WRF urban LC with surrounding natural LC
Looping through urban grid pixels: 100%|█████████████████████████████████████| 4168/4168 [00:33<00:00, 125.69it/s]
--> Create LCZ-based geo_em file
> Processing LP_URB2D ...
> Processing MH_URB2D ...
> Processing STDH_URB2D ...
> Processing HGT_URB2D ...
> Processing LB_URB2D ...
> Processing LF_URB2D ...
> Processing HI_URB2D ...
--> Create LCZ-based urban extent geo_em file (excluding other LCZ-based info)
--> Expanding land categories of parent domain(s) to 41

--> Start sanity check and clean-up ...
> Check 1: Urban class removed from geo_em.d03_NoUrban.nc? OK 
> Check 2: LCZ Urban extent present in geo_em.d03_LCZ_extent.nc? OK 
> Check 3: Urban LCZ classes exists in geo_em.d03_LCZ_params.nc? OK: LCZ Classes ([1, 2, 4, 5, 6, 8, 9, 10]) present 
> Check 4: FRC_URB2D present in geo_em.d03_LCZ_params.nc? OK: FRC_URB2D values range between 0.00 and 0.93 
> Check 5: URB_PARAMS matrix present in file geo_em.d03_LCZ_params.nc? OK 
> Check 6: Do URB_PARAM variable values follow expected range in geo_em.d03_LCZ_params.nc?
   + OK for LP_URB2D 
   + OK for MH_URB2D 
   + OK for STDH_URB2D 
   + OK for HGT_URB2D 
   + OK for LB_URB2D 
   + OK for LF_URB2D 
> Check 7: Does HI_URB2D sum to 100% for urban pixels in geo_em.d03_LCZ_params.nc? OK 
> Check 8: Do FRC_URB and LCZs (from LU_INDEX) cover same extent in geo_em.d03_LCZ_params.nc? OK 
> Check 9: Extent and # urban pixels same for *_extent.nc and *_params.nc output file? OK, urban extent the same (6507) 
> Cleaning up ... all done!


 ----------- !! NOTE !! --------- 
 Set nbui_max to 10 during compilation, in order to optimize memory storage.
```

Note that I did not check the `_add_usgs` implementation itself, nor whether the output makes sense.
Perhaps you can have a look at the output files @lpilz? 
You can get the output from [here](https://drive.google.com/file/d/15YvlTLB30ETgxpVWD-hndhO9yVNCTs3n/view?usp=share_link).

**Comment by lpilz** [comment]
Hi everybody, thanks so much for your help. I tried around a bit yesterday and I'm not sure this is a bug in the `w2w` code. When I submitted the job as batch to my HPC, the execution stalled at https://github.com/matthiasdemuzere/w2w/blob/2cdc57fe9d9a4583cc046fd83f9b67f78214f6ef/w2w/w2w.py#L567

However, I then tried to run it in an interactive session and for some reason that worked. I'm not quite sure why this would make a difference to `w2w`.

@matthiasdemuzere Yes, my plan was to use all three geo_em files with LCZ. I was under the impression that if you had `sf_urban_physics` enabled for a domain, it would be sensible to also generate the LCZ-geo_em files. Is this not the case?

**Comment by dargueso** [comment]
Hi I just checked and it run well for domain 1. I can share the data with you, if you need it. I'm running it now for the other two domains. It took a few hours to complete, though. I have used your version, so the line you mention

https://github.com/matthiasdemuzere/w2w/blob/2cdc57fe9d9a4583cc046fd83f9b67f78214f6ef/w2w/w2w.py#L567

is slightly different (adapted to usgs)

`newluf[is_urban - 1, i, j] = 0.0`

**Comment by lpilz** [comment]
Hi @dargueso, thanks so much. The `w2w` run was successful in the end, so I do have the data. I also used the USGS-adjusted version, but couldn't permalink to the line ;)

**Comment by matthiasdemuzere** [comment]
> @matthiasdemuzere Yes, my plan was to use all three geo_em files with LCZ. I was under the impression that if you had `sf_urban_physics` enabled for a domain, it would be sensible to also generate the LCZ-geo_em files. Is this not the case?

You of course can, yet most people don't. Mainly because they are mostly interested in the intra-urban variability at the finest model resolution (inner domain), and not necessarily within the parent domains ...

**Comment by matthiasdemuzere** [comment]
In general I am happy that this worked out in the end.

@dargueso: have you been able to revise the `_add_usgs_` code changes? Does everything works as expected? 

As far as I understood, there is not much information on the other (memory?) issues? 
To be honest, I am not sure if I want to spend time on this. Mainly because I am currently working with the people and NCAR to get this W2W routine directly into WPS, so that this routine would become obsolete ...

So for the time being I'd like to keep things as they are, unless of course more people bump into this same issue?

**Comment by dargueso** [comment]
@matthiasdemuzere, I've checked the code changes and approved them (I think I did right). They looked correct to me and the code passed the tests as expected.
Yes, I think the other issue is related to memory, but I agree with you, not sure it is worth going after this...

**Comment by matthiasdemuzere** [comment]
Perhaps @theendlessriver13 can have a final look at that pull request and merge when accepted?

Thanks @lpilz for your contribution!

**Comment by lpilz** [comment]
Thanks for your help everybody! Closing this
