### ISSUE TITLE
valueError

### ISSUE THREAD

**Issue by fipoucat** [matthiasdemuzere/w2w#103]
I am facing an error with my work with w2w and wonder what is causing this ? i qm using katest version

--> Create LCZ-based urban extent geo_em file (excluding other LCZ-based info)
--> Expanding land categories of parent domain(s) to 41

--> Start sanity check and clean-up ...
> Check 1: Urban class removed from geo_em.d03_NoUrban.nc? OK 
> Check 2: LCZ Urban extent present in geo_em.d03_LCZ_extent.nc?
 WARNING: LCZ-based urban extent missing 
> Check 3: Urban LCZ classes exists in geo_em.d03_LCZ_params.nc? OK: LCZ Classes ([]) present 
> Check 4: FRC_URB2D present in geo_em.d03_LCZ_params.nc? OK: FRC_URB2D values range between 0.00 and 0.00 
> Check 5: URB_PARAMS matrix present in file geo_em.d03_LCZ_params.nc? OK 
> Check 6: Do URB_PARAM variable values follow expected range in geo_em.d03_LCZ_params.nc?
   + OK for LP_URB2D 
   + OK for MH_URB2D 
   + OK for STDH_URB2D 
   + OK for HGT_URB2D 
   + OK for LB_URB2D 
   + OK for LF_URB2D 
Traceback (most recent call last):
  File "/home/sarr/.local/bin/w2w", line 8, in <module>
    sys.exit(main())
  File "/home/sarr/.local/lib/python3.10/site-packages/w2w/w2w.py", line 200, in main
    checks_and_cleaning(
  File "/home/sarr/.local/lib/python3.10/site-packages/w2w/w2w.py", line 1596, in checks_and_cleaning
    if np.nanmax(np.abs((100 - hi_sum).values)) > 0.1:
  File "<__array_function__ internals>", line 5, in nanmax
  File "/usr/lib/python3/dist-packages/numpy/lib/nanfunctions.py", line 434, in nanmax
    res = np.fmax.reduce(a, axis=axis, out=out, **kwargs)
ValueError: zero-size array to reduction operation fmax which has no identity

**Comment by theendlessriver13** [comment]
duplicate #38

please [search the issue tracker](https://github.com/matthiasdemuzere/w2w/issues?q=is%3Aissue+ValueError%3A+zero-size+array+to+reduction+operation+fmax+which+has+no+identity+is%3Aclosed) and use the issue template as we asked you before: https://github.com/matthiasdemuzere/w2w/issues/93#issuecomment-1250083371

**Comment by fipoucat** [comment]
Hi,

I certainly should mention #38 and seen how that was fixed. I am surprise because I am using the last version and indicated the band in my w2w command, this is why I am posting it in case the error is from another reason?

Thank you

**Comment by theendlessriver13** [comment]
as long as you don't provide a standalone reproduction (following the issue template) there's nothing we can do here. Please comment on #38 to not have things spread out between 2 issues.
