### ISSUE TITLE
Error while processing the global LCZ map

### ISSUE THREAD

**Issue by meteomanic** [matthiasdemuzere/w2w#106]
Hi,
I am trying to inject global wudpat lcz (https://zenodo.org/record/7324909/files/lcz_filter_v2.tif) using w2w and  not able to do a successful injection of WUDAPT data (log file has been attached). The same went well with the given sample data.

For you information, I am using the single domain geo_em data at 2 km horizontal resolution.

Is there any way to fix this issue?

Thanks and regards,
Raghu

[log.txt](https://github.com/matthiasdemuzere/w2w/files/10324217/log.txt)

**Comment by theendlessriver13** [comment]
please use the issue template and search the issue tracker (as requested in the issue template) - closing as duplicate of #98
