### ISSUE TITLE
off-line w2w installation

### ISSUE THREAD

**Issue by Foxcrash2021** [matthiasdemuzere/w2w#110]
### Describe your issue

Hello, staff. I encountered a problem. When I used the command pip install to install w2w directly, my network was very bad, so I could not download and install it successfully. So I downloaded the w2w folder on the website. I want to ask what version of the dependent installation package is required for offline installation of w2w. I am confused about this. Please tell me this. What should I pay attention to when installing these? I don't know much about offline installation of w2w. Thank you

### w2w --version

w2w -0.5.0

### nc-config --all

```console
This netCDF-c-4.7.4 and netCDF-fortran-4.5.3
```

### Installed Packages

```console
none of packages installed
```

**Comment by jkittner** [comment]
The only supported way to install w2w is via `pip install w2w`. There are many, many dependencies, which each have their own dependencies, that needs to be resolved by pip. I think you need to sort out your network issues first, otherwise you'll have a hard time installing anything...
