### ISSUE TITLE
error wrf.exe using lcz

### ISSUE THREAD

**Issue by fipoucat** [matthiasdemuzere/w2w#111]
I am running a test test simulation but noticed an error message related to URBPARM_LCZ:

```
Climate GHG input from file from year         1765  to         2499
 CO2   range =    277.91300000000001        579.26400000000001       ppm
 N2O   range =    274.37200000000001        359.79800000000000       ppb
 CH4   range =    738.98599999999999        997.31100000000004       ppb
 CFC11 range =    0.0000000000000000        1.4000000000000000E-002  ppt
 CFC12 range =    0.0000000000000000        2.8809999999999998       ppt
 Normal ending of CAMtr_volume_mixing_ratio file
 GHG annual values from CAM trace gas file
 Year =         2022 , Julian day =          151
 CO2   =    4.2008633475787584E-004  volume mixing ratio
 N2O   =    3.3358618037029334E-007  volume mixing ratio
 CH4   =    1.9316669843938158E-006  volume mixing ratio
 CFC11 =    2.1285051219760373E-010  volume mixing ratio
 CFC12 =    4.8585826390686277E-010  volume mixing ratio
INPUT LandUse = "MODIFIED_IGBP_MODIS_NOAH"
 LANDUSE TYPE = "MODIFIED_IGBP_MODIS_NOAH" FOUND          61  CATEGORIES           2  SEASONS WATER CATEGORY =           17  SNOW CATEGORY =           15
INITIALIZE THREE Noah LSM RELATED TABLES
Skipping over LUTYPE = USGS
 LANDUSE TYPE = MODIFIED_IGBP_MODIS_NOAH FOUND          20  CATEGORIES
 INPUT SOIL TEXTURE CLASSIFICATION = STAS
 SOIL TEXTURE CLASSIFICATION = STAS FOUND          19  CATEGORIES
-------------- FATAL CALLED ---------------
USING URBPARM_LCZ.TBL WITH OLD 3 URBAN CLASSES. SET USE_WUDAPT_LCZ=0
-------------------------------------------
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```
I am reporting in case someone can help understand and fix the issue.

Thank you

**Comment by matthiasdemuzere** [comment]
@fipoucat Please use the provided template to report issues, so that we know what environment you work in and what w2w / wrf version you use.

@andreazonato have you seen this error before?

**Comment by fipoucat** [comment]
Thank you Mattias, I was able to do the simulation using a restart strategy after reporting the same issue to wrf forum. The problem is mainly due to the size of my inner domain too small because of the adjustment done based on my LCZ map. The causes of number of processor to use with the other domains. I then need a wider LCZ map for my city (Dakar) and wonder how to get it?

**Comment by matthiasdemuzere** [comment]
So you adjusted your WRF domain based on the available LCZ map? That is bad practice.

First you need to decide upon a proper inner WRF domain.
Then you can apply W2W, using an LCZ map that is slightly larger than the WRF domain in all directions.

As indicated in the [W2W JOSS paper](https://joss.theoj.org/papers/10.21105/joss.04432), there are various ways to get your LCZ map: the LCZ Generator, the global LCZ map, ...

Please, always read all documentation in detail, it is there for a reason.

**Comment by andreazonato** [comment]
I agree with @matthiasdemuzere .

The issue is linked to the mismatch between num_land_cat and LCZ. You should correctly provide the number  of classes so WRF can identify it as WUDAPT instead of traditional 31-33 classes

**Comment by matthiasdemuzere** [comment]
You refer to [this submission](https://lcz-generator.rub.de/factsheets/06c1a0faae69f5d888e24ac4d8bf07bdbb29db08/06c1a0faae69f5d888e24ac4d8bf07bdbb29db08_factsheet.html)?

If this geotif fits your needs, you can fill the white areas with label 17 (= G = water), so that it will work with w2w.

**Comment by fipoucat** [comment]
Yes, it is that submission., this geotiff looks fine for my needs. I'll try
to do the filling with QGIS then.

Thank you

**Comment by fipoucat** [comment]
@matthiasdemuzere. I tried but looks it is not possible because this white areas are not in the labels. Any other idea on doing the change?  I have clipped a similar area from the global map but the generated one looks far more accurate.

**Comment by matthiasdemuzere** [comment]
The white areas in the .tif are 0's which you have to replace by value 17 (=water).
As this is a basic geospatial operation, you'll have to figure this one out yourself.

**Comment by fipoucat** [comment]
Ok, thank you
