### ISSUE TITLE
WRF4.4.2 Run CGLC-MODIS-LCZ dataset

### ISSUE THREAD

**Issue by Foxcrash2021** [matthiasdemuzere/w2w#113]
### Describe your issue

<img width="784" alt="2b2f2403ab50efc511e365c6ddbba41" src="https://user-images.githubusercontent.com/94523993/227153006-c62dec78-a789-4b21-98ee-0c34bcd3ec73.png">
<img width="855" alt="ae4d4e2280179abef6d52754b8d5791" src="https://user-images.githubusercontent.com/94523993/227153024-a6fae28a-6fe5-49f0-a037-d65b9a618399.png">

I am running the latest dataset CGLC-MODIS-LCZ dataset using WRF4.4.2. I have specified the location, interpolation method, and landmask description of the data in geogrid.tbl, and then/ Geogrid.exe also succeeded. Check the lu_ Index has 61 categories, and then mine/ Real.exe also succeeded, but mine/ "Wrf.exe failed to run quickly, and what I want to know is whether it failed because I didn't use WRF4.5, or could it run successfully using WRF4.4.2, but where is the problem with my settings?"?

This is my termination interface

### w2w --version

w2w -0.5.0

### nc-config --all

```console
netcdf-c-4.7.4  netcdf-fortran-4.5.3
```

### Installed Packages

```console
numpy==1.23.1
```

**Comment by matthiasdemuzere** [comment]
The use of this new CGLC-MODIS-LCZ dataset will only be supported in the next release of WRF, which is not available yet.
For earlier versions, you can use the W2W tool to ingest LCZ information in your boundary files.

**Comment by Foxcrash2021** [comment]
Well, tanks.can you disclose when the latest WRF 4.5 version will be released?

**Comment by matthiasdemuzere** [comment]
Last I heard was "spring" 2023. I do not know what this means exactly, for that you should probably check the wrf github pages ...

**Comment by Foxcrash2021** [comment]
ok,thanks
