### ISSUE TITLE
LCZ bug

### ISSUE THREAD

**Issue by Foxcrash2021** [matthiasdemuzere/w2w#114]
### Describe your issue

Hello, I encountered a problem when using the LCZ map, that is, I added air conditioner-related variables (such as CM_AC_URB3) to the output variables of WRF, and then I also set the air conditioner on and the start of the air conditioner in URBPARM_LCZ.TBL The data run out at the beginning shows that my CM_AC_URB3, LF_AC_URB3, and SF_AC_URB3 are all 0, but I did not use the LCZ calculation example in which the output of the air conditioner has an output value. What is the reason for this?

### w2w --version

w2w -0.5.0

### nc-config --all

```console
netcdf-c-4.7.4  netcdf-fortran-4.5.3
```

### Installed Packages

```console
numpy==1.23.1
```

**Comment by Foxcrash2021** [comment]
can anyone give me advice?

**Comment by matthiasdemuzere** [comment]
Hi @Foxcrash2021,

To be clear, this is not a 24/7, where you can expect a response as per your request.
We are just a bunch of people trying to help the community building open-source tools, and providing support, mostly in our spare time. So please, show some patience and respect.

Re: your question: I am afraid it is not clear to me. @andreazonato developed the AC routine, so he might be better positioned to unravel what you are really asking for?

**Comment by andreazonato** [comment]
Hi @Foxcrash2021 
Actually you did not give me enough information.
Which WRF version ae you using? can you attach the namelist?

**Comment by Foxcrash2021** [comment]
hi@matthiasdemuzere ,I'm sorry that I was a little anxious, I apologize for my previous behavior, thank you for your reply

**Comment by Foxcrash2021** [comment]
@andreazonato,Hello,my WRF version is 4.3.1, and my input and URBPARM_LCZ.TBL are like this, thanks for your reply, hope to get further communication from you

**Comment by andreazonato** [comment]
@Foxcrash2021,

you should turn on the flag USE_WUDAPT_LCZ=1. 
Moreover, do you see the LCZ in the wrfinputs?

Andrea
