### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by haohe1982** [matthiasdemuzere/w2w#115]
### Describe your issue

I am ruing W2W on my PC anaconda. When processing one geo_em file, it stops and showing the following error:

--> Set data, arguments and files
> Using layer 0 of the LCZ GeoTIFF. Can be changed with -l (--lcz-band)
--> Check LCZ integrity, in terms of class labels, projection and extent
> LCZ labels as expected (1 to 17)
ERROR 1: PROJ: proj_identify: C:\Users\haohe\anaconda3\Library\share\proj\proj.db lacks DATABASE.LAYOUT.VERSION.MAJOR / DATABASE.LAYOUT.VERSION.MINOR metadata. It comes from another PROJ installation.
ERROR 1: PROJ: proj_identify: C:\Users\haohe\anaconda3\Library\share\proj\proj.db lacks DATABASE.LAYOUT.VERSION.MAJOR / DATABASE.LAYOUT.VERSION.MINOR metadata. It comes from another PROJ installation.
> LCZ provided as WGS84 (EPSG:4326)
> LCZ domain is covering WRF domain
--> Replace WRF urban LC with surrounding natural LC
Looping through urban grid pixels: 100%|█████████████████████████████████████████| 19652/19652 [07:13<00:00, 45.38it/s]
--> Create LCZ-based geo_em file
Traceback (most recent call last):
  File "C:\Users\haohe\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\haohe\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\haohe\anaconda3\Scripts\w2w.exe\__main__.py", line 7, in <module>
  File "C:\Users\haohe\anaconda3\lib\site-packages\w2w\w2w.py", line 186, in main
    nbui_max = create_lcz_params_file(
  File "C:\Users\haohe\anaconda3\lib\site-packages\w2w\w2w.py", line 1276, in create_lcz_params_file
    dst_data = _add_frc_lu_index_2_wrf(
  File "C:\Users\haohe\anaconda3\lib\site-packages\w2w\w2w.py", line 1202, in _add_frc_lu_index_2_wrf
    frc_urb = _ucp_resampler(
  File "C:\Users\haohe\anaconda3\lib\site-packages\w2w\w2w.py", line 754, in _ucp_resampler
    lcz_data = np.array(replacer[lcz_arr], dtype='float')
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 15.8 GiB for an array with shape (29356, 72313) and data type object

I have 16GB memory, so how to avoid this error say using virtual memonry?

Thanks

Hao

### w2w --version

w2w 0.5.0 the latest

### nc-config --all

```console
N/A
```

### Installed Packages

```console
N/A
```

**Comment by jkittner** [comment]
yeah, a few people have run into memory issues so far, there are a few duplicates in the issue tracker e.g. #57 - so far there hasn't been any easy solution other than reducing the region size. 

There is the concept of `numpy.memmap` for saving partial results, but I have never worked with it myself, and it would probably require some larger changes to the code.

So I'd suggest checking your domain size, if it really needs to be that big, or unfortunately looking for alternatives for processing.
