### ISSUE TITLE
Not enough natural land points in selected area 

### ISSUE THREAD

**Issue by magalietecher** [matthiasdemuzere/w2w#118]
### Describe your issue

Hi everybody, 

I succesfully use the sample data provided with the tutorial. 
When i use my data: 

> Seems you are using a LCZ map produced by https://lcz-generator.rub.de/
> I therefor use the Gaussian filtered default 'LczFilter' layer
--> Check LCZ integrity, in terms of class labels, projection and extent
> LCZ labels as expected (1 to 17)
> LCZ provided as WGS84 (EPSG:4326)
> LCZ domain is covering WRF domain
--> Replace WRF urban LC with surrounding natural LC
Looping through urban grid pixels:   4%|█▌                                         | 3031/83904 [00:58<25:59, 51.87it/s]

At 4% I have this error, i don't understand: 

### ERROR:  Not enough natural land points in selected area
You chose to sample 45 pixels over an area of 2025 Increase NPIX_AREA.
Traceback (most recent call last):
  File "/home/magalie/miniconda3/lib/python3.9/site-packages/pandas/core/indexes/range.py", line 345, in get_loc
    return self._range.index(new_key)
ValueError: 0 is not in range
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/magalie/miniconda3/lib/python3.9/site-packages/w2w/w2w.py", line 547, in wrf_remove_urban
    mkd = data_luse_natland.iloc[:NPIX_NLC].luse.mode()[0]
  File "/home/magalie/miniconda3/lib/python3.9/site-packages/pandas/core/series.py", line 1007, in __getitem__
    return self._get_value(key)
  File "/home/magalie/miniconda3/lib/python3.9/site-packages/pandas/core/series.py", line 1116, in _get_value
    loc = self.index.get_loc(label)
  File "/home/magalie/miniconda3/lib/python3.9/site-packages/pandas/core/indexes/range.py", line 347, in get_loc
    raise KeyError(key) from err
KeyError: 0

Exiting ...

I am working on Montpellier City and using WRF 4.3. 
 I try the following comand like suggest to modify -n --npix-nlc = 1025
> w2w ./output_montpellier  LCZ_Montpellier.tif geo_em.d01.nc -n --npix-nlc

but I have this error : 

usage: w2w [-h] [-V] [-b  [...]] [-l] [-f] [-n] [-a] [--lcz-ucp LCZ_UCP] io_dir lcz_file wrf_file
w2w: error: argument -n/--npix-nlc: expected one argument

Do you know how I could resolve this issue and modify arguments? 
I am novice in w2w and coding in general.. Any help would be appreciate, thank you in advance!

### w2w --version

w2w 0.5.0

### nc-config --all

```console
WRF 4.3
netcdf-c-4.7.2
netcdf-fortran-4.5.2
```

### Installed Packages

```console

```

**Comment by jkittner** [comment]
duplicate #116

**Comment by magalietecher** [comment]
Hi, 
Little update, I finally find an answer. I did not have enough storage memory to calculate the w2w products because of the high resolution (100m) of my simulation domain.

 I try with lower (200m-1000m) and it works fine. 

Magalie
