### ISSUE TITLE
real.exe ERROR while reading namelist physics

### ISSUE THREAD

**Issue by Zitong1998** [matthiasdemuzere/w2w#120]
### Describe your issue

I have successfully w2w inject WUDAPT's Local Climate Zone information in WRF. But when I run real.exe, the following error occurs. 

```
taskid: 0 hostname: bp1-login01.data.bp.acrc.priv
  module_io_quilt_old.F 2931 T
   ------ ERROR while reading namelist physics ------
Maybe here?: num_land_cat = 41,
Maybe here?: num_urban_nbui = 5,
-------------- FATAL CALLED ---------------
FATAL CALLED FROM FILE: <stdin> LINE: 11164
ERRORS while reading one or more namelists from namelist.input.
-----------------------------------------------
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
:
system msg for write_line failure : Bad file descriptor
```

My namelist.input file and rsl.error file are as attached. May I ask where I am doing wrong?
My WRF version is 4.3.1 and WPS version is 4.3.

[namelist.txt](https://github.com/matthiasdemuzere/w2w/files/12344827/namelist.txt)
[rsl.error.txt](https://github.com/matthiasdemuzere/w2w/files/12344828/rsl.error.txt)

### w2w --version

w2w 0.5.0

### nc-config --all

```console
netcdf-c-4.9.0  netcdf-fortran-4.6.0
```

### Installed Packages

```console
numpy == 1.25.1
```

**Comment by matthiasdemuzere** [comment]
@andreazonato, any ideas?

**Comment by andreazonato** [comment]
Hi @Zitong1998,

you should delete num_urban_nbui, WRF calculates it automatically.
(and maybe you should use 61 landuse classes, depending on which WRF version you are using)

Cheers,

Andrea
