### ISSUE TITLE
deprecation warning in `xarray.open_rasterio`

### ISSUE THREAD

**Issue by theendlessriver13** [matthiasdemuzere/w2w#16]
we encountered this before in another project, however this time we are also supporting python 3.6. `xarray` and `rioxarray` only support `>=3.7`
https://github.com/pydata/xarray/blob/main/setup.cfg#L77
https://github.com/corteva/rioxarray/blob/master/setup.py#L74

So when installing rioxarray on 3.6. it installs `0.3.1` and `xarray==0.16.2` but on >= 3.7 it installs `rioxarray==0.8.0` and `xarray==0.17`. On 3.6 when switiching to `rioxarray.open_rasterio` (the non deprecated way) it errors with `AttributeError: 'DataArray' object has no attribute 'transform'`.

So my suggestion would be to drop 3.6 support when it is officiall EOL (2021-12-23) to resolve this deprecation warning.

The fixes would be:
1. swap all `xr.open_rasterio` to `rioxarray.open_rasterio`
1. change `python_requires` to `python_requires=">=3.7"` in `setup.cfg`
1. update GitHub Action python version and the tox.ini file

**Comment by matthiasdemuzere** [comment]
As we are close to the EOL of 3.6, could we not already remove this support? 
And then already apply the fixes you suggest00?

**Comment by theendlessriver13** [comment]
okay, let us first finish #12 and then make a separate PR for dropping `3.6`.
