### ISSUE TITLE
Calculation of Euclidian distance based on geographical coordinates

### ISSUE THREAD

**Issue by KlemensBarfus** [matthiasdemuzere/w2w#19]
In `wrf_remove_urban:` distance is calculated as Euclidian distance based on  geographical coordinates (lat & lon): 

` dis = (lat.where((luse!=13) &  
                                 (luse!=17) &  
                                 (luse!=21)  
                                 )-lat.isel(south_north=i,west_east=j))**2 +\  
                      (lon.where((luse!=13) &  
                                 (luse!=17) &  
                                 (luse!=21)  
                                 )-lon.isel(south_north=i,west_east=j))**2`   
 

Due to meridian convergence, there might be some issues with Euclidian distance calculation with the magnitude of the issues not clear to me. I would suggest to use array indices for distance calculation (with the same effect as projected coordinates).

**Comment by matthiasdemuzere** [comment]
Thanks for this remark @KlemensBarfus.

@dargueso designed this routine, perhaps he can have a look whether this can be optimised?

**Comment by dargueso** [comment]
Yes, you're right. This was originally designed for cities near the equator, so it wasn't much of an issue. I will update it to calculate distances taking that into account.
Thanks @KlemensBarfus.

**Comment by dargueso** [comment]
I have added a function to calculate distance using a better approximation (spherical law of cosines).  I have added a pull request for this.
