### ISSUE TITLE
metgrid.exe crashed when using the *.nc files generated by w2w.py

### ISSUE THREAD

**Issue by Zhengzefeng1999** [matthiasdemuzere/w2w#2]
Hello everyone!

I'm new to WRF and I want to simulate the temperature in urban areas of Fuzhou, China. After reading the [paper](https://doi.org/10.3389/fenvs.2021.637455) about [LCZ-generator](https://lcz-generator.rub.de/), I'm interested in the work of using LCZ classification results to replace the default urban areas in WRF(as you did here). I successfully generated an LCZ map of Fuzhou city by using the LCZ-generator, so I decided to use the results in my WRF model.

After getting the LCZ map, I was curious about how to use the results in my WRF model. But fortunately, I found the repo of [w2w](https://github.com/matthiasdemuzere/w2w) soon, and I try to follow the workflow of w2w to generate the NetCDF file that contains the LCZ results of mine, everything went perfect and I got the three files(*_NoUrban.nc, *_LCZ_extent.nc and *_LCZ_params.nc) by using the w2w.py, but things went wrong during ./metgrid.exe after replacing my geo_em.d04.nc file from these three files, I got the error message as below:
_ERROR: Couldn't open file ./geo_em.d04.nc for input._

Maybe there is somewhere I didn't follow correctly? I copied geo_em.d04_LCZ_params.nc to my WPS folder and rename it to geo_em.d04.nc so I can use it in metgrid.exe, but unfortunately, the error message above occurred when processing domain 4 of 4(received the same message when using *_NoUrban.nc and *_LCZ_params.nc)

Here I attached my METGRID.TBL and the log file of metgrid
[METGRID_TBL.txt](https://github.com/matthiasdemuzere/wrf-lcz-KL/files/6701113/METGRID_TBL.txt)
[metgrid.log](https://github.com/matthiasdemuzere/wrf-lcz-KL/files/6701068/metgrid.log)

namelist.input and namelist.wps may also need
[namelist_input.txt](https://github.com/matthiasdemuzere/wrf-lcz-KL/files/6701280/namelist_input.txt)
[namelist_wps.txt](https://github.com/matthiasdemuzere/wrf-lcz-KL/files/6701281/namelist_wps.txt)

I would be very grateful if you can help solve my problem!

Best Wishes

Zefeng Zheng

**Comment by Zhengzefeng1999** [comment]
Hi Daniel,

Thanks for helping! 

My WRF is the latest version 4.3,  I downloaded the source code [here](https://github.com/wrf-model/WRF)

I attached all the geo_em.d0X.nc files generated by geogrid.exe, and the *.nc files generated by w2w.py. I also put the LCZ map generated by LCZ-generator inside the .zip file.
[geo_em_data.zip](https://github.com/matthiasdemuzere/w2w/files/6702529/geo_em_data.zip)

Hope you can find the problem soon!

Best,
Zefeng Zheng

**Comment by andreazonato** [comment]
hi @Zhengzefeng1999 ,

thank you for your interest in our tool.

I tried your  geo_em_d04, with your namelist (renaming it removing the .txt) and GFS 0.25x0.25  (ds084.1) for boundary conditions, and actually it works fine for all the geo_em_d04.

Do you still have this problem?

Andrea

**Comment by Zhengzefeng1999** [comment]
Hi Andrea,

I'm sorry for the late reply and thank you for helping me with the problem and testing my file.

> I tried your geo_em_d04, with your namelist (renaming it removing the .txt) and GFS 0.25x0.25 (ds084.1) for boundary conditions, and actually it works fine for all the geo_em_d04.

Well, I'm glad to hear that you can run it successfully with my geo_em.d04.* files, but unfortunately, mine still don't work with the same problem. I replaced the geo_em.d04.nc back to the file generated by geogrid.exe, it works fine, and once use the new geo_em.d04 files, the problem occurred again. So that may be my PC's problem(compiler, environment variables or the dependency repos I guess), I will list something that may be helpful(I guess) below.

OS: Ubuntu 20.04
compiler: gfortran, gcc, g++, all of them are 9.3.0 
mpich-3.4.1
NetCDF-4.5.3
jasper-1.900.1
libpng-1.6.37
zlib-1.2.11

If all of the above can not be the cause of the problem and you need other files to locate it, I'm glad to share them.

Thanks,
Zefeng Zheng

**Comment by Zhengzefeng1999** [comment]
Well, I just try it on another PC and my num_land_cat in the geo_em.d0X.nc is 21. After using the w2w.py, three new *_41.nc file generated successfully, but after I replace the geo_em.d0X.nc files generated by geogrid.exe to these new files, the program crashed at the first domain with the same error message(_ERROR: Couldn't open file ./geo_em.d01.nc for input._). So I guess there is somewhere I didn't set up correctly causing the metgrid.exe can't open(or how to say, recognize?) the file generated by w2w.py on my PC(I ran the whole procedure under the **w2w** environment).

The new geo_em.* files attached.
[geo_em.d0X.nc.zip](https://github.com/matthiasdemuzere/w2w/files/6710452/geo_em.d0X.nc.zip)

I'd appreciate it if you can figure out what causes the error!

Best,
Zefeng Zheng

**Comment by dargueso** [comment]
Dear Zefeng Zheng, 
I have also tried with the geo_em files you sent with WPS 4.3 and it all went fine with metgrid.exe, didn’t get an error.
I have renamed the geo_em.d0X_41.nc to geo_em.d0X.nc. And then tried separately for all the geo_em.d04_*.nc the w2w generates (geo_em.d04_NoUrban.nc, geo_em.d04_LCZ_params.nc and geo_em.d04_LCZ_extent.nc) previously renaming them to geo_em.d04.nc and they all went OK. I have used ERA5 this time and the namelist.wps you provided. I have used the default METGRID.TBL for ECMWF data. 

I’ve run it in two different machines, both with Ubuntu. 
I’m sorry but we cannot replicate your error, so it is hard for us to identify what may be causing this.

Best,
Daniel

**Comment by Zhengzefeng1999** [comment]
Hi Daniel,

First I have to thank you for helping to test my files!

> I have also tried with the geo_em files you sent with WPS 4.3 and it all went fine with metgrid.exe, didn’t get an error. I have renamed the geo_em.d0X_41.nc to geo_em.d0X.nc. And then tried separately for all the geo_em.d04_*.nc the w2w generates (geo_em.d04_NoUrban.nc, geo_em.d04_LCZ_params.nc and geo_em.d04_LCZ_extent.nc) previously renaming them to geo_em.d04.nc and they all went OK. I have used ERA5 this time and the namelist.wps you provided. I have used the default METGRID.TBL for ECMWF data.

Well, I'm glad to hear that you run it successfully, but that's strange for me, I redownloaded and recompiled the WRF and WPS(but didn't change the environment variables) then rerun geogrid and replace the geo_em.d04.nc before metgrid.exe, the error still occurs. When I use the _ncdump -h geo_em.d04_*_ command under the **base** environment to check the headers, it didn't work with the following message: **_ncdump: geo_em.d04.nc: geo_em.d04.nc: NetCDF: Attempt to use feature that was not turned on when netCDF was built._**, but it works fine under the **w2w** environment, I think this can't be the cause of the error because the whole program should be tested under the **w2w** environment, can it?

Since both of you and Andrea can run all my files in all conditions without error, then the problem must caused by my PCs, so I think I should reinstall all of the files relative to WRF, and set the environment variables again. If you have any other suggestions for solving this problem, I'm glad to adopt them.

I will leave a comment here once I have any progress, and if I need some relative files, would you like to share with me?

At last, Thanks again to all of you guys!

Best,
Zefeng Zheng

**Comment by dargueso** [comment]
Hi Zefeng Zheng,
From what you say, it looks like it may be related to the netCDF libraries in your computer, but I can’t really say what exactly.
The w2w environment is probably using its own netCDF libraries and they are not compatible with your installation. I’m just guessing, but hard to say from here.
Please let us know you’re progress. 
Best,
Daniel

**Comment by Zhengzefeng1999** [comment]
Hi Daniel,

Thanks for the suggestion, I will try it later and leave a comment after that.

Best,
Zefeng Zheng

**Comment by matthiasdemuzere** [comment]
Hi @Zhengzefeng1999 

If you used the anaconda environment to run w2w, then you are using a contained python installation for this w2w code.

Assuming you compile WRF outside the anaconda environment, this compilation is using your system's libraries.
So I agree with @dargueso that your issue is probably due to your local netcdf environment (make sure netcdf4 and hdf5 is enabled)??

Two side notes:
- since you use the LCZ map from the Generator, make sure you use the w2w argument `-lcz_band 1`, to use the lczFilter band of the lcz .tif
- I had a quick look at your LCZ map. I do think it makes sense to spend a bit more time in improving the map, to avoid areas that seems misclassified. Eg. the tidal areas along the coast line are mapped as LCZ1, while they should probably be water (LCZ 17/G). or bare soil/sand (LCZ 16/F). The best way to address such issues is to add polygons to areas that seem wrong, and then submit your new training area data to the LCZ Generator. Guidelines on how to digitize are [here](https://www.wudapt.org/digitize-training-areas/).

**Comment by Zhengzefeng1999** [comment]
Hi @matthiasdemuzere 

> If you used the anaconda environment to run w2w, then you are using a contained python installation for this w2w code

Yes, I installed the w2w through anaconda.

> Assuming you compile WRF outside the anaconda environment, this compilation is using your system's libraries.
> So I agree with @dargueso that your issue is probably due to your local netcdf environment (make sure netcdf4 and hdf5 is enabled)??

OK, I got it, I will try it later and rerun it again.

> * since you use the LCZ map from the Generator, make sure you use the w2w argument `-lcz_band 1`, to use the lczFilter band of the lcz .tif

Yes, I followed the instructions of the important notes in this repo, using the argument `-lcz_band 1` to generate the file.

> * I had a quick look at your LCZ map. I do think it makes sense to spend a bit more time in improving the map, to avoid areas that seems misclassified. Eg. the tidal areas along the coast line are mapped as LCZ1, while they should probably be water (LCZ 17/G). or bare soil/sand (LCZ 16/F). The best way to address such issues is to add polygons to areas that seem wrong, and then submit your new training area data to the LCZ Generator. Guidelines on how to digitize are [here](https://www.wudapt.org/digitize-training-areas/)

Indeed, you are right, the quality isn't that good for this LCZ map, this is not the one for the final simulation, just a sample data for me to test whether the workflow works great on my PC, so I will take your advice to improve it later.

Thanks for giving the advice!

Best,
Zefeng Zheng

**Comment by Zhengzefeng1999** [comment]
Hi guys,

First I want to say thank you to all of you, I succeed in running _metgrid.exe_.

> From what you say, it looks like it may be related to the netCDF libraries in your computer, but I can’t really say what exactly. The w2w environment is probably using its own netCDF libraries and they are not compatible with your installation. I’m just guessing, but hard to say from here.

> Assuming you compile WRF outside the anaconda environment, this compilation is using your system's libraries.
> So I agree with @dargueso that your issue is probably due to your local netcdf environment (make sure netcdf4 and hdf5 is enabled)??

Yes, indeed, that's due to the netCDF and HDF5 libraries as @dargueso and @matthiasdemuzere mentioned. I recompiled the WRF and I found I didn't enable the HDF5 while the compilation(using classic netCDF), but after I reinstall the netCDF and HDF5 libraries and then compile the WRF, the compilation failed. I searched the reason for the error, the answer is that I should not use the new version netCDF-Fortran-4.5.3(I originally used), then I downloaded an older version of 4.4.4, and finally, the compilation finished with no error. 

But I found another problem while _real.exe_, it crashed when using SLUCM(`sf_urban_physics = 1` in namelist.input) with the error message: **ZDC + Z0C + 2m is larger than the 1st WRF level - Stop in subroutine urban - change ZDC and Z0C**, but the program finished successfully while the `sf_urban_physics = 2`(3 I didn't try yet), and in the **wrf-lcz-kl**, I remember you guys noted that you failed with SLUCM, is the error message same with yours? If so, is that still an issue?

Whatever, thank you guys for helping me with the problem, this issue solved successfully.

Best,
Zefeng Zheng

**Comment by andreazonato** [comment]
Hi @Zhengzefeng1999 ,

great you solved the issue with libraries!

Regarding the problem with the real, since you are using the SINGLE layer UCM, by definition it runs with a single layer, and all  the first WRF level should be > than you highest building. Two possibilities to solve the issue:

1) Increase the first WRF level 
2) smooth a bit the highest buildings to allow a higher resolution for the first level


Andrea

**Comment by Zhengzefeng1999** [comment]
Hi @andreazonato,

OK, I will try it, Thank you.

Zefeng Zheng

**Comment by TianhangZhang** [comment]
Hello Zefeng, 
i have the same error. i set three domains. I do not know how to solve this
ERROR: Error in ext_pkg_open_for_write_begin.
ERROR: Couldn't open file ./geo_em.d03.nc for input.
I can get met_em.d01 and d02 but cannot get d03
[error.txt](https://github.com/matthiasdemuzere/w2w/files/7797629/error.txt)

here is my namelist.wps
&share
 wrf_core = 'ARW',
 max_dom = 3,
 start_date = '2018-01-24_00:00:00','2018-01-24_00:00:00','2018-01-24_00:00:00',
 end_date   = '2018-01-25_00:00:00','2018-01-25_00:00:00','2018-01-25_00:00:00',
 interval_seconds = 3600,
 io_form_geogrid = 2,
/

&geogrid
 parent_id         =   1,   1, 2,
 parent_grid_ratio =   1,   5, 5,
 i_parent_start    =   1,  75, 106,
 j_parent_start    =   1,  12, 87,
 e_we              = 145, 301,891,
 e_sn              = 100 , 381,1281,
 geog_data_res = 'default','default','default',
 dx = 25000,
 dy = 25000,
 map_proj = 'lambert',
 ref_lat   =  53.2,
 ref_lon   = -18.9,
 truelat1  =  53.2,
 truelat2  =  53.2,
 stand_lon = -18.9,
 geog_data_path = '/mnt/iusers01/fatpou01/sees01/a59246tz/Build_WRF/WPS_GEOG/'
/

&ungrib
 out_format = 'WPS',
 prefix = 'SFCFILE',
/

&metgrid
 fg_name = 'SFCFILE','ATMFILE',
 io_form_metgrid = 2,
/

thank you
tianhang

**Comment by Zhengzefeng1999** [comment]
Hello @TianhangZhang 

If your WRF was not compiled with NetCDF4/HDF5 libraries, then you can follow the routine of this issue, some other people sucessfully solve the same problem as mine through my way (#9, #23) .

Best,
Zefeng

**Comment by TianhangZhang** [comment]
> 
How to recompile netcdf4/hdf5, i used hpc of  my university, I just use code module load libs/gcc/netcdf/4.6.2 to download netcdf, do I need to recompile wps and wrf again?

**Comment by Zhengzefeng1999** [comment]
@TianhangZhang  Sorry I don't know how to make it on hpc, but if you need to compile your WRF through HDF5, then you should recompile WRF again.

Zefeng

**Comment by josephcannon38** [comment]
Hello @Zhengzefeng1999 

I am having a similar issue to the one you had. Since compiling WRF with the NETCDF4/HDF5 libraries worked for you to resolve the issue, I have been trying to do the same thing. I am having a hard time figuring out how to install WRF with these libraries enabled though. I know on WRF's website when they install WRF in their installation tutorial they disable netcdf4, but I can't successfully build when I try to enable it. Could you walk me through how to install with these enabled? Thank you. 

Joseph

**Comment by Zhengzefeng1999** [comment]
@josephcannon38  Sorry for the late reply, does the issue still exist?
