### ISSUE TITLE
Number of surrounding pixels for calculation of 'newluse' is 44 though NPIX_NLC = 45

### ISSUE THREAD

**Issue by KlemensBarfus** [matthiasdemuzere/w2w#22]
Not clear to me why this happens, but e.g for i=166, j=84 of the attached example only 44 surrounding pixels are used (though NPIX_NLC is set to 45) to derive the new landuse in 
`aux = luse.where(dis<disflat.sortby(disflat)
                                 .isel(gridpoints=NPIX_NLC),drop=True)
  newluse[i,j]=int(mode(aux.values.flatten())[0])`

Is there a reason for that ?
- this was tested with the old distance calculation

[geo_em.d03.zip](https://github.com/matthiasdemuzere/w2w/files/7703588/geo_em.d03.zip)

**Comment by KlemensBarfus** [comment]
Many thanks for clarification !

**Comment by matthiasdemuzere** [comment]
Closing this now. Feel free to re-open in case needed.
