### ISSUE TITLE
metgrid.exe cannot read the generated nc file

### ISSUE THREAD

**Issue by Liuzh223** [matthiasdemuzere/w2w#23]
Hello,I  followed your steps to run successfully to get the geo_em.d03_LCZ_params.nc file and renamed the file to geo_em.d03.nc . When I attempt to run metgrid.exe, I get the following "ERROR: Couldn't open file ./geo_em.d03.nc for input".How could I solve this problem?Thanks! This is the information of my two files.
<img width="344" alt="geo_em d03 nc" src="https://user-images.githubusercontent.com/96330239/146633351-b35f1360-3dd7-4a13-8df7-02df47ea8a0d.PNG">
<img width="351" alt="geo_em d03_LCZ_params" src="https://user-images.githubusercontent.com/96330239/146633358-fcb09a3e-a08d-4866-adec-8f9555d7ee51.PNG">
.

**Comment by Zhengzefeng1999** [comment]
Hello,

Make sure your WRF was compiled with NetCDF/HDF5 libraries, maybe you can follow the issue of mine #2 or #9.

Best,
Zefeng

**Comment by Liuzh223** [comment]
Thanks for your reply.I will try it.

**Comment by Liuzh223** [comment]
Hello@Zhengzefeng1999 ,

I successfully ran metgrid.exe as your solution, and I also successfully ran sf_urban_physics = 2 city model, however, I ran sf_urban_physics = 3, there was a problem. The error is shown in the figure, what should I do?

<img width="449" alt="error" src="https://user-images.githubusercontent.com/96330239/146948204-f38d5455-0d03-4298-a92d-ede62ecaccde.PNG">

Best，
Lz

**Comment by Zhengzefeng1999** [comment]
Hi Lz,

Since you ran BEP option `sf_urban_physics = 2` successfully but failed with BEM `sf_urban_physics = 3`, I think you must have turned on the feedback option `feedback = 1` in &domains part of namelist.input, I don't know why the modified file can't work with BEM when the feedback option is on, maybe this problem should ask @matthiasdemuzere @dargueso @andreazonato .

If the feedback option is not necessary to you, now you can turn off the feedback option `feedback = 0`.

Best,
Zefeng

**Comment by matthiasdemuzere** [comment]
> Since you ran BEP option `sf_urban_physics = 2` successfully but failed with BEM `sf_urban_physics = 3`, I think you must have turned on the feedback option `feedback = 1` in &domains part of namelist.input, I don't know why the modified file can't work with BEM when the feedback option is on, maybe this problem should ask @matthiasdemuzere @dargueso @andreazonato .

 @dargueso @andreazonato: This issue is still open, I am not sure about this feedback option. Is this something we should address? Even if just a note in the JOSS documentation?

**Comment by andreazonato** [comment]
@matthiasdemuzere , no idea about this error. 
I don't know if feedback=1 resolved the issue. Anyway, I think this is not related to w2w, but instead to BEP+BEM

**Comment by Liuzh223** [comment]
My teacher told me that this option has little impact on my research, so this has been resolved. Since I haven't logged in for a long time, this issue is still open, I'm very sorry. I will set it to close. Thanks a lot for your help!!

**Comment by dargueso** [comment]
We've run the v4.3 with SF_URBAN_PHYSICS = 3 and FEEDBACK = 0 successfully for a few-year simulation over Kuala Lumpur. I haven't tried with FEEDBACK = 1. 

It looks like it is possible to run both configurations with LCZ according to your paper (attached), @andreazonato. But I haven't explored this myself. 

[Ribeiroetal2021.pdf](https://github.com/matthiasdemuzere/w2w/files/8131288/Ribeiroetal2021.pdf)
h
