### ISSUE TITLE
ZDC + Z0C + 2m is larger than the 1st WRF level (SLUCM)

### ISSUE THREAD

**Issue by matthiasdemuzere** [matthiasdemuzere/w2w#4]
Moving the section below to a new issue, for clarity ...

But I found another problem while _real.exe_, it crashed when using SLUCM(`sf_urban_physics = 1` in namelist.input) with the error message: **ZDC + Z0C + 2m is larger than the 1st WRF level - Stop in subroutine urban - change ZDC and Z0C**, but the program finished successfully while the `sf_urban_physics = 2`(3 I didn't try yet), and in the **wrf-lcz-kl**, I remember you guys noted that you failed with SLUCM, is the error message same with yours? If so, is that still an issue?

Whatever, thank you guys for helping me with the problem, this issue solved successfully.

Best,
Zefeng Zheng

_Originally posted by @Zhengzefeng1999 in https://github.com/matthiasdemuzere/w2w/issues/2#issuecomment-869598189_

**Comment by matthiasdemuzere** [comment]
Originally written by @andreazonato

Hi @Zhengzefeng1999 ,

great you solved the issue with libraries!

Regarding the problem with the real, since you are using the SINGLE layer UCM, by definition it runs with a single layer, and all the first WRF level should be > than you highest building. Two possibilities to solve the issue:

Increase the first WRF level
smooth a bit the highest buildings to allow a higher resolution for the first level
Andrea

**Comment by matthiasdemuzere** [comment]
Hi @Zhengzefeng1999 ,

Did you manage to solve the issue with the building heights - model layer heights?

Matthias

**Comment by Zhengzefeng1999** [comment]
Hi @matthiasdemuzere 

I'm sorry for didn't update my latest work here. 

For this problem, I know how to solve it soon after Andrea reply me. But for my work, I finally decided to use BEP+BEM to run the model, so I didn't change the WRF level or the building height to satisfy the SLUCM. The model ran successfully using `sf_urban_physics = 2 or 3`, and I got a good result by using BEP+BEM.

Now I'm trying to update the Land Use/Land Cover from MODIS products([MCD12Q1v006](https://lpdaac.usgs.gov/products/mcd12q1v006/)). I'm still learning, and everything goes smoothly so far.

If I have any problem or question, I'll open another issue here.

Best,
Zefeng Zheng

**Comment by Liuzh223** [comment]
Hi @matthiasdemuzere 

I recently modified URBPARM_LCZ.TBL parameters, such as FRC_URB2D, BUILD_HEIGHT. It did not work. This problem has troubled me for a long time.

I saw you mentioned that the solution to this problem is to reduce the value of ZR, so I would like to ask you, does it work when you modify the TBL parameters?

Best,
Zhuo Liu

**Comment by matthiasdemuzere** [comment]
@andreazonato: can you answer this one? Thanks!

**Comment by andreazonato** [comment]
> Hi @matthiasdemuzere
> 
> I recently modified URBPARM_LCZ.TBL parameters, such as FRC_URB2D, BUILD_HEIGHT. It did not work. This problem has troubled me for a long time.
> 
> I saw you mentioned that the solution to this problem is to reduce the value of ZR, so I would like to ask you, does it work when you modify the TBL parameters?
> 
> Best, Zhuo Liu


It should not matter if you modified those parameters. Was it working before? What errors is WRF giving to you?

**Comment by Zhengzefeng1999** [comment]
Her confusion is why she modified the parameters (FRC_URB2D and BUILD_HEIGHT) in the TBL but did not show any difference in the output. 
Since the problem is not about the tool and she has contacted me, I will help her solve the problem.

**Comment by matthiasdemuzere** [comment]
Ok. So as far as I understand, @Liuzh223 changed the values of FRC_URB2D, BUILD_HEIGHT in URBPARM_LCZ.TBL.

Yet this will not work. 

As indicated in the JOSS paper, the morphological urban canopy parameter values are provided in `LCZ_UCP_default.csv` and not in `URBPARM_LCZ.TBL`  (see **Procedure 1** in JOSS).

Information of `URBPARM_LCZ.TBL` is only used to assign radiative and thermal parameters to the modal LCZ class (see **Procedure 2** in JOSS).

Morphological user-specific parameters can be used, by using a custom look-up table, as explain [here](https://github.com/matthiasdemuzere/w2w#arguments).

I hope this helps.

**Comment by andreazonato** [comment]
I Agree with @matthiasdemuzere . If you employ the W2W tool, urban GEOMETRICAL parameters are taken from the wrfinput_d0* (FRC_URB2D,BUILD_HEIGHT, HEIGHT_HISTOGRAMS,BUILD_SURF_RATIO and BUILD_AREA FRACTION). Only the other parameters (thermal, roughness lengths, air conditioning, mitigation strategies) are taken from URBPARM_LCZ.TBL.

Hope my explanation is clear

Andrea

**Comment by Liuzh223** [comment]
I'm really very grateful to you for help. That teach me a lot, but I still have a question. If I want to modify these geometric parameters, what should i do, whether i can only modify them in the LCZ_UCP_default.csv file.

**Comment by matthiasdemuzere** [comment]
Please follow the guidelines in the README.

I suggest you copy `LCZ_UCP_default.csv` to eg. `LCZ_UCP_custom.csv`, and change the required values in the latter file.
Then use the dedicated argument to use your custom file, e.g.:

`w2w ./sample_data lcz_zaragoza.tif geo_em.d04.nc --lcz-ucp path/to/LCZ_UCP_custom.csv`


You might also want to check Issue #92, indicating that:
1) there should be no spaces in the column headers of the table.
2) the building height properties (MIN, MEAN, MAX) should not be all equal.

Good luck.

**Comment by Liuzh223** [comment]
Thanks a lot for your help. I will try.

Best,
Zhuo Liu
