### ISSUE TITLE
TypeError: Argument 'image' has incorrect type (expected numpy.ndarray, got DataArray)

### ISSUE THREAD

**Issue by yy522** [matthiasdemuzere/w2w#40]
Hi I got this error when processing the continental LCZ map for US with my domain in Los Angeles. It looks like an error occurring with the rasterio package. As suggested, I used the LCZ map ends with 'epsg4326'. This error occurred after the screen shows '+ FRC_URB2D, alter LU_INDEX, GREENFRAC and LANDUSEF'. What could be wrong here? Thanks!

<img width="833" alt="image" src="https://user-images.githubusercontent.com/44189600/155283271-5285bd60-19f5-4793-973d-439819f45e5c.png">

**Comment by yy522** [comment]
I think the error is related the use of an old version of rasterio package. I upgraded it by 'pip install --upgrade rasterio' and the message wasn't shown any more. Will follow up with any further issues.

**Comment by theendlessriver13** [comment]
Thanks for having a look at this, so we might have to add a lower version bound.

Would you mind bisecting which version of `rasterio` breaks this? Maybe you can also send a PR adding this to here:
https://github.com/matthiasdemuzere/w2w/blob/9b4fb44843e96d8559a8a7511522200f60ec79db/setup.cfg#L27 for instance `rasterio>=0.1.2`

I would first have a look at the change from `0.*` to `1.*` most likely it's this. Or which version did you have installed?

**Comment by yy522** [comment]
Thank you. So the message is here:
<img width="355" alt="image" src="https://user-images.githubusercontent.com/44189600/155369998-4ee46037-7838-4036-9c1c-cd67aa925c49.png">
The old version 1.1.3 broke the W2W procedure. The latest version 1.2.10 worked well.

However, I haven't had the whole procedure run successfully. I got a kill:9 issue and am retrying now. Here's the current outputs to the screen. At least there are no more error about image type.
<img width="515" alt="image" src="https://user-images.githubusercontent.com/44189600/155370643-99620b2b-1a42-4a42-b8b5-e68dc5803c0c.png">

**Comment by matthiasdemuzere** [comment]
Hi @yy522 

Did you manage to process all data?
Any feedback on the rasterio versions (lower bounds) that should not be used?

Thanks!
