### ISSUE TITLE
Error while installing w2w

### ISSUE THREAD

**Issue by lippinpauly** [matthiasdemuzere/w2w#58]
Hi everyone, I am a beginner in WRF analysis and new to this field. Currently, my research is to studying urban micro climate. Thanks, @matthiasdemuzere and team for this amazing w2w to explore the urban environment.  Coming to my problem, while I'm **installing w2w using pip**, I encounter the following error. I really appreciate any help you guys can provide. Many thanks in advance.

 error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.
      ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by lippinpauly** [comment]
Maybe I tried to install it in windows right? w2w is compatible only with the Linux environment?

**Comment by lippinpauly** [comment]
Error is showing in Windows. Now I installed it in Linux and it is working. Thank you

**Comment by theendlessriver13** [comment]
It also works on windows.
However installing some of the dependecies is tricky - you'd have to have gdal setup properly and the correct environment variables set to be able to build wheels.
Installing from pre built wheels is also an option.

But I agree, using this and other tools on linux saves a lot of stress and time.

**Comment by lippinpauly** [comment]
Thank you @theendlessriver13. Currently, I am using w2w on my university computer(Linux) and it works fine. However, If I need to install it in the future, I may need little help from you regarding procedures and I will contact you. Thanks again..!
