### ISSUE TITLE
TypeError: only size-1 arrays can be converted to Python scalars

### ISSUE THREAD

**Issue by Hanfly96** [matthiasdemuzere/w2w#59]
@theendlessriver13 @dargueso @andreazonato @matthiasdemuzere 
Hi，when I use the tiff from LCZ generator, I met this problem.  
My WRF is the latest version 4.3.1, I downloaded the source code [here](https://github.com/wrf-model/WRF), and w2w is the latest version 0.2.0
I attached all the geo_em.d0X.nc files generated by geogrid.exe. I also put the LCZ map generated by LCZ-generator inside the .zip file.
[w2w2.zip](https://github.com/matthiasdemuzere/w2w/files/8752334/w2w2.zip)
1.`(base) [ac7a1iq56s@login07 w2w2]$ w2w -l 1 ~/w2w2 beijing4.tif geo_em.d03.nc
--> Set data, arguments and files 
> Seems you are using a LCZ map produced by https://lcz-generator.rub.de/ 
> I therefor use the Gaussian filtered default 'LczFilter' layer
--> Check LCZ integrity, in terms of class labels, projection and extent
> LCZ labels as expected (1 to 17)
> LCZ provided as WGS84 (EPSG:4326)
> LCZ domain is covering WRF domain
--> Replace WRF MODIS urban LC with surrounding natural LC
Traceback (most recent call last):
  File "/public/home/ac7a1iq56s/anaconda3/bin/w2w", line 8, in <module>
    sys.exit(main())
  File "/public/home/ac7a1iq56s/anaconda3/lib/python3.9/site-packages/w2w/w2w.py", line 150, in main
    wrf_remove_urban(
  File "/public/home/ac7a1iq56s/anaconda3/lib/python3.9/site-packages/w2w/w2w.py", line 494, in wrf_remove_urban
    newlu = int(m) - 1
TypeError: only size-1 arrays can be converted to Python scalars`

2.`(base) [ac7a1iq56s@login07 w2w2]$ w2w ~/w2w2 beijing4.tif geo_em.d03.nc
--> Set data, arguments and files 
> Seems you are using a LCZ map produced by https://lcz-generator.rub.de/ 
> I therefor use the Gaussian filtered default 'LczFilter' layer
--> Check LCZ integrity, in terms of class labels, projection and extent
> LCZ labels as expected (1 to 17)
> LCZ provided as WGS84 (EPSG:4326)
> LCZ domain is covering WRF domain
--> Replace WRF MODIS urban LC with surrounding natural LC
Traceback (most recent call last):
  File "/public/home/ac7a1iq56s/anaconda3/bin/w2w", line 8, in <module>
    sys.exit(main())
  File "/public/home/ac7a1iq56s/anaconda3/lib/python3.9/site-packages/w2w/w2w.py", line 150, in main
    wrf_remove_urban(
  File "/public/home/ac7a1iq56s/anaconda3/lib/python3.9/site-packages/w2w/w2w.py", line 494, in wrf_remove_urban
    newlu = int(m) - 1
TypeError: only size-1 arrays can be converted to Python scalars'

I would be very grateful if you can help solve my problem!

Best Wishes
Fei Han

**Comment by matthiasdemuzere** [comment]
@dargueso: seems to be an issue in your `wrf_remove_urban()` routine? Could you have a look?

**Comment by theendlessriver13** [comment]
![grafik](https://user-images.githubusercontent.com/54631600/169775883-e1654041-4987-4ef3-9b97-009349b23916.png)
It looks like if there is only one class "17" in the netcdf input file? This seems to be the issue causing the type error.

**Comment by Hanfly96** [comment]
Thank you very much for your reply! 
The problem does lie with land use data.


Thanks again,
Fei Han
