### ISSUE TITLE
[w2w error] CRS not found / invalid projection

### ISSUE THREAD

**Issue by FloBre33** [matthiasdemuzere/w2w#63]
Hi, I'm running into an issue of projection or Coordinate Reference System (CRS) when running w2w to prepare a domain with LCZs for a WRF simulation. 

Running this line (adapted to my case):

`
w2w INPUT_DATA LCZ.tif geo_em.d0X.nc
`

results in:

 ```
←[1m--> Set data, arguments and files ←[0m
 Seems you are using a LCZ map produced by https://lcz-generator.rub.de/
 I therefor use the Gaussian filtered default 'LczFilter' layer
 ←[1m--> Check LCZ integrity, in terms of class labels, projection and extent←[0m
 LCZ labels as expected (1 to 17)
 Traceback (most recent call last):
   File "C:\Users\admin\miniconda3\lib\runpy.py", line 197, in _run_module_as_main
     return _run_code(code, main_globals, None,
   File "C:\Users\admin\miniconda3\lib\runpy.py", line 87, in _run_code
     exec(code, run_globals)
   File "C:\Users\admin\miniconda3\Scripts\w2w.exe\__main__.py", line 7, in <module>
   File "C:\Users\admin\miniconda3\lib\site-packages\w2w\w2w.py", line 144, in main
     check_lcz_integrity(
   File "C:\Users\admin\miniconda3\lib\site-packages\w2w\w2w.py", line 350, in check_lcz_integrity
     lcz = lcz.rio.reproject('EPSG:4326')
   File "C:\Users\admin\miniconda3\lib\site-packages\rioxarray\raster_array.py", line 433, in reproject
     raise MissingCRS(
 rioxarray.exceptions.MissingCRS: CRS not found. Please set the CRS with 'rio.write_crs()'.
```

Now, when I use `rio.write_crs` to set the CRS, the following happens:

  ```
xda = xarray.DataArray('C:\\Postdoc\\Taches\\Simulations\\Description_villes\\Strasbourg\\LCZ\\w2w\\input\\lcz_wudapt_ponche.tif')
  xda.rio.write_crs(4326, inplace=True)
 ERROR 1: PROJ: proj_create_from_database: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name
 ERROR 1: PROJ: proj_as_wkt: DatumEnsemble can only be exported to WKT2:2018
 Traceback (most recent call last):
   File "rasterio\_crs.pyx", line 195, in rasterio._crs._CRS.to_wkt
   File "rasterio\_err.pyx", line 205, in rasterio._err.exc_wrap_ogrerr
 rasterio._err.CPLE_BaseError: OGR Error code 6
 During handling of the above exception, another exception occurred:
 Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "C:\Users\admin\miniconda3\lib\site-packages\rioxarray\rioxarray.py", line 464, in write_crs
     grid_map_attrs = pyproj.CRS.from_user_input(data_obj.rio.crs).to_cf()
   File "C:\Users\admin\miniconda3\lib\site-packages\pyproj\crs\crs.py", line 488, in from_user_input
     return cls(value, **kwargs)
   File "C:\Users\admin\miniconda3\lib\site-packages\pyproj\crs\crs.py", line 310, in __init__
     if projparams:
   File "C:\Users\admin\miniconda3\lib\site-packages\rasterio\crs.py", line 83, in __bool__
     return bool(self.wkt)
   File "C:\Users\admin\miniconda3\lib\site-packages\rasterio\crs.py", line 143, in wkt
     self._wkt = self.to_wkt()
   File "C:\Users\admin\miniconda3\lib\site-packages\rasterio\crs.py", line 131, in to_wkt
     return self._crs.to_wkt(morph_to_esri_dialect=morph_to_esri_dialect)
   File "rasterio\_crs.pyx", line 198, in rasterio._crs._CRS.to_wkt
 rasterio.errors.CRSError: Cannot convert to WKT. OGR Error code 6
```

This is what the CRS looks like in the file:
 ```
rds = xarray.open_dataset('C:\\Postdoc\\Taches\\Simulations\\Description_villes\\Strasbourg\\LCZ\\w2w\\input\\lcz_wudapt_ponche.tif')
 rds.spatial_ref
<xarray.DataArray 'spatial_ref' ()>
array(0)
Coordinates:
    spatial_ref  int32 0
Attributes:
    GeoTransform:  7.465898326317343 0.0008983152841195215 0.0 48.76863845956...
```

The LCZ.tif file was prepared with WUDAPT: [link to LCZ Generator factsheet](https://lcz-generator.rub.de/factsheets/524e8ea612a50ad8794501668684e5f534a075b9/524e8ea612a50ad8794501668684e5f534a075b9_factsheet.html).

I'm confused about how to solve this CRS/projection issue. I'm also surprised that this issue has not yet been raised by other people (on the forum). 

Any help, please?

**Comment by matthiasdemuzere** [comment]
Hi @FloBre33,

Could you also share your geo_em file here, so that I can have a closer look?

In addition, can you also share more information about your python environment (version + versions of all packages). This behaviour might be in line with something @dargueso previously reported, for a specific version of rioxarray. Though that was something I could not reproduce myself.

**Comment by FloBre33** [comment]
Thank you Matthias for the quick response.

You can find the geo_em files (and namelists) here: [https://seafile.unistra.fr/d/885b20e2dab44542be4c/](https://seafile.unistra.fr/d/885b20e2dab44542be4c/). The goal is to include LCZs in domain 4 for Strasbourg metropolis (France).

My Python version is 3.9.12 and the versions of the modules are:
```
w2w==0.3.0
  - ecmwflibs [required: Any, installed: 0.4.17]
    - findlibs [required: Any, installed: 0.0.2]
  - numpy [required: >=1.21, installed: 1.22.4]
  - pandas [required: Any, installed: 1.4.2]
    - numpy [required: >=1.18.5, installed: 1.22.4]
    - python-dateutil [required: >=2.8.1, installed: 2.8.2]
      - six [required: >=1.5, installed: 1.16.0]
    - pytz [required: >=2020.1, installed: 2022.1]
  - rasterio [required: >=1.1.6, installed: 1.2.10]
    - affine [required: Any, installed: 2.3.1]
    - attrs [required: Any, installed: 21.4.0]
    - certifi [required: Any, installed: 2022.5.18.1]
    - click [required: >=4.0, installed: 8.1.3]
      - colorama [required: Any, installed: 0.4.4]
    - click-plugins [required: Any, installed: 1.1.1]
      - click [required: >=4.0, installed: 8.1.3]
        - colorama [required: Any, installed: 0.4.4]
    - cligj [required: >=0.5, installed: 0.7.2]
      - click [required: >=4.0, installed: 8.1.3]
        - colorama [required: Any, installed: 0.4.4]
    - numpy [required: Any, installed: 1.22.4]
    - setuptools [required: Any, installed: 61.2.0]
    - snuggs [required: >=1.4.1, installed: 1.4.7]
      - numpy [required: Any, installed: 1.22.4]
      - pyparsing [required: >=2.1.6, installed: 3.0.9]
  - rioxarray [required: Any, installed: 0.11.1]
    - packaging [required: Any, installed: 21.3]
      - pyparsing [required: >=2.0.2,!=3.0.5, installed: 3.0.9]
    - pyproj [required: >=2.2, installed: 3.3.1]
      - certifi [required: Any, installed: 2022.5.18.1]
    - rasterio [required: >=1.1.1, installed: 1.2.10]
      - affine [required: Any, installed: 2.3.1]
      - attrs [required: Any, installed: 21.4.0]
      - certifi [required: Any, installed: 2022.5.18.1]
      - click [required: >=4.0, installed: 8.1.3]
        - colorama [required: Any, installed: 0.4.4]
      - click-plugins [required: Any, installed: 1.1.1]
        - click [required: >=4.0, installed: 8.1.3]
          - colorama [required: Any, installed: 0.4.4]
      - cligj [required: >=0.5, installed: 0.7.2]
        - click [required: >=4.0, installed: 8.1.3]
          - colorama [required: Any, installed: 0.4.4]
      - numpy [required: Any, installed: 1.22.4]
      - setuptools [required: Any, installed: 61.2.0]
      - snuggs [required: >=1.4.1, installed: 1.4.7]
        - numpy [required: Any, installed: 1.22.4]
        - pyparsing [required: >=2.1.6, installed: 3.0.9]
    - xarray [required: >=0.17, installed: 2022.3.0]
      - numpy [required: >=1.18, installed: 1.22.4]
      - packaging [required: >=20.0, installed: 21.3]
        - pyparsing [required: >=2.0.2,!=3.0.5, installed: 3.0.9]
      - pandas [required: >=1.1, installed: 1.4.2]
        - numpy [required: >=1.18.5, installed: 1.22.4]
        - python-dateutil [required: >=2.8.1, installed: 2.8.2]
          - six [required: >=1.5, installed: 1.16.0]
        - pytz [required: >=2020.1, installed: 2022.1]
```
Cheers,
FB

**Comment by dargueso** [comment]
Hi @FloBre33, 
I also encountered this error. Apparently, it has to do with rioxarray version (0.11), but it is related to other packages or the environment, because @matthiasdemuzere couldn't reproduce it with that rioxarray version. We need to investigate. In the meantime, I solved it by creating a new environment with a lower version number.

**Comment by theendlessriver13** [comment]
We previously had reports where old `rasterio` versions caused issued e.g. #40. Because of this we set a lower bound requirement for `rasterio` to `>=1.1.6` in our `setup.cfg` in #50. This version was the first one that worked at the time I tested it. @FloBre33 seems to have the latest version of `rasterio` installed (`[required: >=1.1.6, installed: 1.2.10]`) which is the same version our tests run against [see here](https://github.com/matthiasdemuzere/w2w/runs/6857627975?check_suite_focus=true). So this has to be related to the dataset itself being different in some way or as @dargueso mentioned some other side effect caused by other packages which technically _should_ not happen.

**Comment by FloBre33** [comment]
I tried to correct the CRS, which seemed to work with rioxarray v0.7.1:
```
>>> rds = xarray.open_dataset('C:\\Postdoc\\Taches\\Simulations\\Description_villes\\Strasbourg\\LCZ\\w2w\\input\\lcz_wudapt_ponche.tif')
>>> rds.spatial_ref
<xarray.DataArray 'spatial_ref' ()>
array(0)
Coordinates:
    spatial_ref  int32 0
Attributes:
    crs_wkt:                      GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["...
    semi_major_axis:              6378137.0
    semi_minor_axis:              6356752.314245179
    inverse_flattening:           298.257223563
    reference_ellipsoid_name:     WGS 84
    longitude_of_prime_meridian:  0.0
    prime_meridian_name:          Greenwich
    geographic_crs_name:          WGS 84
    grid_mapping_name:            latitude_longitude
    spatial_ref:                  GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["...
    GeoTransform:                 7.465898326317343 0.0008983152841195215 0.0...
>>> rds.rio.write_crs(4326,inplace=True)
<xarray.Dataset>
Dimensions:      (band: 3, x: 603, y: 435)
Coordinates:
  * band         (band) int32 1 2 3
  * x            (x) float64 7.466 7.467 7.468 7.469 ... 8.004 8.005 8.006 8.007
  * y            (y) float64 48.77 48.77 48.77 48.77 ... 48.38 48.38 48.38 48.38
    spatial_ref  int32 0
Data variables:
    band_data    (band, y, x) float32 ...
```
However, w2w still doesn't see the CRS:
```
w2w C:/Postdoc/Taches/Simulations/Description_villes/Strasbourg/LCZ/w2w/input lcz_wudapt_ponche.tif geo_em.d04.nc
←[1m--> Set data, arguments and files ←[0m
> Seems you are using a LCZ map produced by https://lcz-generator.rub.de/
> I therefor use the Gaussian filtered default 'LczFilter' layer
←[1m--> Check LCZ integrity, in terms of class labels, projection and extent←[0m
> LCZ labels as expected (1 to 17)
Traceback (most recent call last):
  File "C:\Users\admin\miniconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\admin\miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\admin\miniconda3\Scripts\w2w.exe\__main__.py", line 7, in <module>
  File "C:\Users\admin\miniconda3\lib\site-packages\w2w\w2w.py", line 144, in main
    check_lcz_integrity(
  File "C:\Users\admin\miniconda3\lib\site-packages\w2w\w2w.py", line 350, in check_lcz_integrity
    lcz = lcz.rio.reproject('EPSG:4326')
  File "C:\Users\admin\miniconda3\lib\site-packages\rioxarray\raster_array.py", line 392, in reproject
    raise MissingCRS(
rioxarray.exceptions.MissingCRS: CRS not found. Please set the CRS with 'rio.write_crs()'.
```

**Comment by dargueso** [comment]
I have two environments. One reproduces the error (proj), the other doesn't (w2w). There are many differences between the two, so it may not only be the rioxarray package, it may be a combination. 

conda list -n proj
conda list -n w2w
In only proj
poppler                  0.81.0    h031bf0f_2          defaults            
mkl_fft                  1.3.1     py39h4ab4a9b_0      defaults            
mkl-service              2.4.0     py39h9ed2024_0      defaults            
glib                     2.69.1    h8346a28_1          defaults            
lz4-c                    1.9.3     h23ab428_1          defaults            
libspatialite            4.3.0a    h268bb56_20         defaults            
wrapt                    1.14.1    py39h701faf5_0      conda-forge         
typing_extensions        4.2.0     pyha770c72_1        conda-forge         
geotiff                  1.7.0     hf77b895_0          defaults            
openjpeg                 2.4.0     h66ea3da_0          defaults            
numpy-base               1.22.3    py39h3b1a694_0      defaults            
libkml                   1.3.0     hbe12b63_4          defaults            
mkl                      2021.4.0  hecd8cb5_637        defaults            
xerces-c                 3.2.3     h48eee30_0          defaults            
wrf-python               1.3.4.1   py39h9d06488_1      conda-forge         
zstd                     1.5.2     hcb37349_0          defaults            
libdap4                  3.19.1    h3d3e54a_0          defaults            
pcre                     8.45      h23ab428_0          defaults            
libwebp-base             1.2.2     hca72f7f_0          defaults            
intel-openmp             2021.4.0  hecd8cb5_3538       defaults            
libpq                    12.9      h1c9f633_1          defaults            
blas                     1.0       mkl                 defaults            
libboost                 1.67.0    hebc422b_4          defaults            
freexl                   1.0.6     h9ed2024_0          defaults            
tiledb                   2.3.3     heb2f9ea_1          defaults            
poppler-data             0.4.11    hecd8cb5_0          defaults            
fontconfig               2.13.1    ha9ee91d_0          defaults            
kealib                   1.4.14    h7cdcae2_1          defaults            
geos                     3.8.0     hb1e8313_0          defaults            
cairo                    1.16.0    h691a603_2          defaults            
gdal                     3.0.2     py39h339f5b9_2      defaults            
json-c                   0.13.1    h3efe00b_0          defaults            
mkl_random               1.2.2     py39hb2f4e1b_0      defaults            
libgdal                  3.0.2     h11ecec2_2          defaults            
cfitsio                  3.470     h01dc385_7          conda-forge         
pixman                   0.40.0    h9ed2024_1          defaults            
gettext                  0.21.0    h7535e17_0          defaults            
proj                     6.2.1     hfd5b9e3_0          defaults            
giflib                   5.2.1     haf1e3a3_0          defaults            
freetype                 2.11.0    hd8bbffd_0          defaults            
libxml2                  2.9.14    hbf8cd5e_0          defaults            
libtiff                  4.2.0     hdb42f99_1          defaults            
libiconv                 1.16      hca72f7f_2          defaults            

In only w2w
pygments                 2.10.0    pyhd3eb1b0_0        defaults            
debugpy                  1.5.1     py39he9d5cce_0      defaults            
pyqt                     5.9.2     py39h23ab428_6      defaults            
notebook                 6.4.6     py39hecd8cb5_0      defaults            
iniconfig                1.1.1     pyhd3eb1b0_0        defaults            
tornado                  6.1       py39h9ed2024_0      defaults            
nbconvert                6.1.0     py39hecd8cb5_0      defaults            
prometheus_client        0.12.0    pyhd3eb1b0_0        defaults            
traitlets                5.1.1     pyhd3eb1b0_0        defaults            
ipython_genutils         0.2.0     pyhd3eb1b0_1        defaults            
ncview                   2.1.8     h90db0c5_2          conda-forge         
terminado                0.9.4     py39hecd8cb5_0      defaults            
libsodium                1.0.18    h1de35cc_0          defaults            
argon2-cffi              20.1.0    py39h9ed2024_1      defaults            
qtconsole                5.1.1     pyhd3eb1b0_0        defaults            
pytest                   6.2.5     py39hecd8cb5_2      defaults            
jupyter_client           7.0.6     pyhd3eb1b0_0        defaults            
ptyprocess               0.7.0     pyhd3eb1b0_2        defaults            
qtpy                     1.10.0    pyhd3eb1b0_0        defaults            
jedi                     0.18.0    py39hecd8cb5_1      defaults            
pyrsistent               0.18.0    py39hca72f7f_0      defaults            
appnope                  0.1.2     py39hecd8cb5_1001   defaults            
pickleshare              0.7.5     pyhd3eb1b0_1003     defaults            
jupyterlab_widgets       1.0.0     pyhd3eb1b0_1        defaults            
bleach                   4.0.0     pyhd3eb1b0_0        defaults            
pyzmq                    22.3.0    py39he9d5cce_2      defaults            
qt                       5.9.7     h468cd18_1          defaults            
pluggy                   1.0.0     py39hecd8cb5_0      defaults            
testpath                 0.5.0     pyhd3eb1b0_0        defaults            
pandocfilters            1.4.3     py39hecd8cb5_1      defaults            
prompt-toolkit           3.0.20    pyhd3eb1b0_0        defaults            
mistune                  0.8.4     py39h9ed2024_1000   defaults            
send2trash               1.8.0     pyhd3eb1b0_1        defaults            
jupyter_console          6.4.0     pyhd3eb1b0_0        defaults            
jsonschema               3.2.0     pyhd3eb1b0_2        defaults            
py                       1.10.0    pyhd3eb1b0_0        defaults            
jupyter_core             4.9.1     py39hecd8cb5_0      defaults            
toml                     0.10.2    pyhd3eb1b0_0        defaults            
ipywidgets               7.6.5     pyhd3eb1b0_1        defaults            
matplotlib-inline        0.1.2     pyhd3eb1b0_2        defaults            
nbformat                 5.1.3     pyhd3eb1b0_0        defaults            
ipykernel                6.4.1     py39hecd8cb5_1      defaults            
webencodings             0.5.1     py39hecd8cb5_1      defaults            
async_generator          1.10      pyhd3eb1b0_0        defaults            
ipython                  7.29.0    py39h01d92e1_0      defaults            
jupyter                  1.0.0     py39hecd8cb5_7      defaults            
nbclient                 0.5.3     pyhd3eb1b0_0        defaults            
backcall                 0.2.0     pyhd3eb1b0_0        defaults            
pexpect                  4.8.0     pyhd3eb1b0_3        defaults            
sip                      4.19.13   py39h23ab428_0      defaults            
nest-asyncio             1.5.1     pyhd3eb1b0_0        defaults            
prompt_toolkit           3.0.20    hd3eb1b0_0          defaults            
widgetsnbextension       3.5.1     py39hecd8cb5_0      defaults            
jupyterlab_pygments      0.1.2     py_0                defaults            
parso                    0.8.2     pyhd3eb1b0_0        defaults            
entrypoints              0.3       py39hecd8cb5_0      defaults            
udunits2                 2.2.25    h05b40f6_1          defaults            
defusedxml               0.7.1     pyhd3eb1b0_0        defaults            
decorator                5.1.0     pyhd3eb1b0_0        defaults            
zeromq                   4.3.4     h23ab428_0          defaults            
wcwidth                  0.2.5     pyhd3eb1b0_0        defaults            

In both, same version:
libnghttp2               1.46.0    ha29bfda_0          defaults            
libffi                   3.3       hb1e8313_2          defaults            
findlibs                 0.0.2     pypi_0              pypi                
libgfortran              5.0.0     9_3_0_h6c81a4c_23   conda-forge         
icu                      58.2      h0a44026_3          defaults            
webob                    1.8.7     pypi_0              pypi                
w2w                      0.2.0     pypi_0              pypi                
appdirs                  1.4.4     pypi_0              pypi                
python_abi               3.9       2_cp39              conda-forge         
docopt                   0.6.2     pypi_0              pypi                
asciitree                0.3.3     pypi_0              pypi                
pydap                    3.2.2     pypi_0              pypi                
libcxx                   12.0.0    h2f01273_0          defaults            
netcdf4                  1.5.8     pypi_0              pypi                
curl                     7.82.0    hca72f7f_0          defaults            
numcodecs                0.9.1     pypi_0              pypi                
ncurses                  6.3       hca72f7f_2          defaults            
libgfortran5             9.3.0     h6c81a4c_23         conda-forge         
libcurl                  7.82.0    h6dfd666_0          defaults            
krb5                     1.19.2    hcd88c3b_0          defaults            
pyparsing                3.0.4     pyhd3eb1b0_0        defaults            
idna                     3.3       pypi_0              pypi                
pip                      21.2.4    py39hecd8cb5_0      defaults            
libedit                  3.1.20210910hca72f7f_0          defaults            
openssl                  1.1.1o    hfe4f2af_0          conda-forge         
libpng                   1.6.37    ha441bb4_0          defaults            

Packages in both, with differnt versions:
pytz :
    proj           2022.1    pyhd8ed1ab_0        conda-forge         
    w2w            2021.3    pypi_0              pypi                
zipp :
    proj           3.8.0     pyhd8ed1ab_0        conda-forge         
    w2w            3.6.0     pyhd3eb1b0_0        defaults            
libssh2 :
    proj           1.10.0    h0a4fc7d_0          defaults            
    w2w            1.10.0    h52ee1ee_2          conda-forge         
ca-certificates :
    proj           2022.5.18.1h033912b_0          conda-forge         
    w2w            2021.10.8 h033912b_0          conda-forge         
urllib3 :
    proj           1.26.9    pypi_0              pypi                
    w2w            1.26.7    pypi_0              pypi                
eccodes :
    proj           1.4.2     pypi_0              pypi                
    w2w            1.4.0     pypi_0              pypi                
requests :
    proj           2.27.1    pypi_0              pypi                
    w2w            2.26.0    pypi_0              pypi                
bzip2 :
    proj           1.0.8     h1de35cc_0          defaults            
    w2w            1.0.8     h0d85af4_4          conda-forge         
soupsieve :
    proj           2.3.2.post1pypi_0              pypi                
    w2w            2.3.1     pypi_0              pypi                
cfgrib :
    proj           0.9.10.1  pypi_0              pypi                
    w2w            0.9.9.1   pypi_0              pypi                
setuptools :
    proj           61.2.0    py39hecd8cb5_0      defaults            
    w2w            58.0.4    py39hecd8cb5_0      defaults            
fasteners :
    proj           0.17.3    pypi_0              pypi                
    w2w            0.16.3    pypi_0              pypi                
h5py :
    proj           3.7.0     pypi_0              pypi                
    w2w            3.6.0     pypi_0              pypi                
xz :
    proj           5.2.5     hca72f7f_1          defaults            
    w2w            5.2.5     h1de35cc_0          defaults            
zlib :
    proj           1.2.12    h4dc903c_2          defaults            
    w2w            1.2.11    h1de35cc_3          defaults            
jpeg :
    proj           9e        hca72f7f_0          defaults            
    w2w            9d        h9ed2024_0          defaults            
zarr :
    proj           2.11.3    pypi_0              pypi                
    w2w            2.10.3    pypi_0              pypi                
click-plugins :
    proj           1.1.1     pyhd3eb1b0_0        defaults            
    w2w            1.1.1     pypi_0              pypi                
scipy :
    proj           1.8.1     pypi_0              pypi                
    w2w            1.7.3     pypi_0              pypi                
pycparser :
    proj           2.21      pypi_0              pypi                
    w2w            2.21      pyhd3eb1b0_0        defaults            
python :
    proj           3.9.12    hdfd78df_1          defaults            
    w2w            3.9.7     h88f2d9e_1          defaults            
xarray :
    proj           2022.3.0  pyhd8ed1ab_0        conda-forge         
    w2w            0.20.2    pypi_0              pypi                
numpy :
    proj           1.22.3    py39h2e5f0a9_0      defaults            
    w2w            1.21.4    pypi_0              pypi                
hdf5 :
    proj           1.10.6    nompi_hc5d9132_1114 conda-forge         
    w2w            1.12.1    nompi_h2f0ef1a_100  conda-forge         
attrs :
    proj           21.4.0    pyhd3eb1b0_0        defaults            
    w2w            21.2.0    pyhd3eb1b0_0        defaults            
markupsafe :
    proj           2.1.1     pypi_0              pypi                
    w2w            2.0.1     py39h9ed2024_0      defaults            
python-dateutil :
    proj           2.8.2     pyhd8ed1ab_0        conda-forge         
    w2w            2.8.2     pyhd3eb1b0_0        defaults            
sqlite :
    proj           3.38.3    h707629a_0          defaults            
    w2w            3.36.0    hce871da_0          defaults            
libzip :
    proj           1.8.0     h272c8d6_0          defaults            
    w2w            1.8.0     h8b0c345_1          conda-forge         
rioxarray :
    proj           0.11.1    pypi_0              pypi                
    w2w            0.9.0     pypi_0              pypi                
beautifulsoup4 :
    proj           4.11.1    pypi_0              pypi                
    w2w            4.10.0    pypi_0              pypi                
tk :
    proj           8.6.12    h5d9f67b_0          defaults            
    w2w            8.6.11    h7bc2e8c_0          defaults            
importlib_metadata :
    proj           4.11.4    hd8ed1ab_0          conda-forge         
    w2w            4.8.2     hd3eb1b0_0          defaults            
click :
    proj           8.0.4     py39hecd8cb5_0      defaults            
    w2w            8.0.3     pypi_0              pypi                
importlib-metadata :
    proj           4.11.4    py39h6e9494a_0      conda-forge         
    w2w            4.8.2     py39hecd8cb5_0      defaults            
expat :
    proj           2.4.4     he9d5cce_0          defaults            
    w2w            2.2.10    h1c7c35f_0          conda-forge         
snuggs :
    proj           1.4.7     pyhd3eb1b0_0        defaults            
    w2w            1.4.7     pypi_0              pypi                
tzdata :
    proj           2022a     hda174b7_0          defaults            
    w2w            2021e     hda174b7_0          defaults            
packaging :
    proj           21.3      pyhd8ed1ab_0        conda-forge         
    w2w            21.3      pyhd3eb1b0_0        defaults            
cligj :
    proj           0.7.2     py39hecd8cb5_0      defaults            
    w2w            0.7.2     pypi_0              pypi                
fsspec :
    proj           2022.5.0  pypi_0              pypi                
    w2w            2021.11.1 pypi_0              pypi                
jinja2 :
    proj           3.1.2     pypi_0              pypi                
    w2w            3.0.2     pyhd3eb1b0_0        defaults            
libev :
    proj           4.33      h9ed2024_1          defaults            
    w2w            4.33      haf1e3a3_1          conda-forge         
certifi :
    proj           2022.5.18.1py39h6e9494a_0      conda-forge         
    w2w            2021.10.8 py39h6e9494a_2      conda-forge         
charset-normalizer :
    proj           2.0.12    pypi_0              pypi                
    w2w            2.0.9     pypi_0              pypi                
h5netcdf :
    proj           1.0.0     pypi_0              pypi                
    w2w            0.11.0    pypi_0              pypi                
pooch :
    proj           1.6.0     pypi_0              pypi                
    w2w            1.5.2     pypi_0              pypi                
cffi :
    proj           1.15.0    pypi_0              pypi                
    w2w            1.14.6    py39h2125817_0      defaults            
pyproj :
    proj           3.3.1     pypi_0              pypi                
    w2w            3.3.0     pypi_0              pypi                
affine :
    proj           2.3.0     pyhd3eb1b0_0        defaults            
    w2w            2.3.0     pypi_0              pypi                
hdf4 :
    proj           4.2.13    h39711bb_2          defaults            
    w2w            4.2.15    hefd3b78_3          conda-forge         
llvm-openmp :
    proj           12.0.0    h0dcd299_1          defaults            
    w2w            14.0.3    ha654fa7_0          conda-forge         
libnetcdf :
    proj           4.8.1     h24cb85c_1          defaults            
    w2w            4.8.1     nompi_h6609ca0_101  conda-forge         
wheel :
    proj           0.37.1    pyhd3eb1b0_0        defaults            
    w2w            0.37.0    pyhd3eb1b0_1        defaults            
pandas :
    proj           1.4.2     pypi_0              pypi                
    w2w            1.3.5     pypi_0              pypi                
c-ares :
    proj           1.18.1    hca72f7f_0          defaults            
    w2w            1.18.1    h0d85af4_0          conda-forge         
ecmwflibs :
    proj           0.4.15    pypi_0              pypi                
    w2w            0.4.0     pypi_0              pypi                
readline :
    proj           8.1.2     hca72f7f_1          defaults            
    w2w            8.1       h9ed2024_0          defaults            
rasterio :
    proj           1.2.10    py39h42baa9d_0      defaults            
    w2w            1.2.10    pypi_0              pypi                
six :
    proj           1.16.0    pyhd3eb1b0_1        defaults            
    w2w            1.16.0    pyhd3eb1b0_0        defaults            
cftime :
    proj           1.6.0     pypi_0              pypi                
    w2w            1.5.1.1   pypi_0              pypi

**Comment by dargueso** [comment]
I have created a new environment with the latest available version of all packages (including rioxarray 0.11.1) and it worked fine. I couldn't reproduce the error. So I guess it may be due to incompatibility with older versions of packages.

**Comment by theendlessriver13** [comment]
We are still having trouble reproducing. We tried with all the versions you provided above on both ubuntu and windows.

Could you maybe provide a very detailed step by step guide how you can reproduce this issue? With other stuff mixed into the w2w environment it is very hard to figure out which one causes this. apparently you @FloBre33 are able to reproduce this reliably, so it would be nice if you could start from a clean environment again, setting up w2w and just paste your complete unchanged terminal output in here, including a list of all installed packages (ideally using `pip freeze`). We hope to figure out what is causing this from that point.

**Comment by FloBre33** [comment]
Thank you a lot of the feedback! About the reliability of error reproduction, I just tried with the sample data and got the same issue. So the issue probably has to do with environment/packages rather than input files. 

I'll do exactly what you suggested (@theendlessriver13) and post it below. BRB

**Comment by dargueso** [comment]
> We are still having trouble reproducing. We tried with all the versions you provided above on both ubuntu and windows.
> 
> Could you maybe provide a very detailed step by step guide how you can reproduce this issue? With other stuff mixed into the w2w environment it is very hard to figure out which one causes this. apparently you @FloBre33 are able to reproduce this reliably, so it would be nice if you could start from a clean environment again, setting up w2w and just paste your complete unchanged terminal output in here, including a list of all installed packages (ideally using `pip freeze`). We hope to figure out what is causing this from that point.

Hi @theendlessriver13, sorry if there was too much information there. I only intended to show that creating new environments  works fine and some of my previous environments didn't reproduce the error either. I did all the tests with the sample data, so the error does come from incompatibilities between packages. I'm unable to provide a detailed step by step because I have built this environment in different stages over the last year or so - if I create a new environment with only the necessary packages and the same versions, I don't get the error.

**Comment by theendlessriver13** [comment]
@dargueso all good! What I suspect is, that we should pin a package with `>=` which we currently do not do. So if the package is already installed, but not with the latest version, it might not be updated. So I'm trying to narrow it down as good as possible. Pinning everything we have will make w2w likely incompatible in every multi purpose environment so I'd like to avoid that.

**Comment by FloBre33** [comment]
Sorry, I'm quite new to Python. 

So I created a new virtual environment in Python (v3.8.11), activated it and installed w2w there (with dependencies). 

I then ran w2w with the sample data successfully. Same with my own data ! :)

Here are the package versions: 
```
(venv) (base) [fbreton@hpc-login1 WRFInputs]$ pip freeze
affine==2.3.1
appdirs==1.4.4
asciitree==0.3.3
attrs==21.4.0
beautifulsoup4==4.11.1
certifi==2022.6.15
cffi==1.15.0
cfgrib==0.9.10.1
cftime==1.6.0
charset-normalizer==2.0.12
click==8.1.3
click-plugins==1.1.1
cligj==0.7.2
docopt==0.6.2
eccodes==1.4.2
ecmwflibs==0.4.17
fasteners==0.17.3
findlibs==0.0.2
fsspec==2022.5.0
h5netcdf==1.0.0
h5py==3.7.0
idna==3.3
importlib-metadata==4.11.4
importlib-resources==5.8.0
Jinja2==3.1.2
MarkupSafe==2.1.1
netCDF4==1.5.8
numcodecs==0.9.1
numpy==1.22.4
packaging==21.3
pandas==1.4.2
pooch==1.6.0
pycparser==2.21
Pydap==3.2.2
pyparsing==3.0.9
pyproj==3.3.1
python-dateutil==2.8.2
pytz==2022.1
rasterio==1.2.10
requests==2.28.0
rioxarray==0.11.1
scipy==1.8.1
six==1.16.0
snuggs==1.4.7
soupsieve==2.3.2.post1
urllib3==1.26.9
w2w==0.3.0
WebOb==1.8.7
xarray==2022.3.0
zarr==2.11.3
zipp==3.8.0
```
Thank you a lot for all the quick and detailed feedback!

Cheers,
Florentin

**Comment by matthiasdemuzere** [comment]
Glad to see this worked out for you @FloBre33!
