### ISSUE TITLE
incorporate data of d03 into d02

### ISSUE THREAD

**Issue by sunqiccgk** [matthiasdemuzere/w2w#70]
Hi professors，I attended the WMO meeting a few days ago, and I am really interested in your LCZ map which can be used in WRF-urban.
Nowdays I am using w2w, I have some questions to consult you. I have three domains, however d03 is so small because of the tiff region is quite small, so I want to incorporate d03_para.nc data into d02_41.nc to replace the original information, 
1. even if in the d03 the grid number is same with d02, the  lat and lon is not same, should I interpolate the d03 data into d02 grid?
2. which variables have be modified in the d03_para.nc (LU_INDEX, LANDUSEF, GREENFRAC, FRC_URB2D, anything else?)
3. if I add d03 into d02 ,there are still some regions in d03 LU_INDEX is 13, so for this LU_INDEX, which urban parameters will be used for them? because the URBPARM_LCZ.TBL don't have this class, right? and d01 will still use URBPARM.TBL or use URBPARM_LCZ.TBL if use_ewudapt_lcz =1 for LU_INDEX =13?
4. in JOSS draft step 4 you mentioned, URB_PARAM is given by LCZ_UCP_default.csv, so in the URBPARM_LCZ.TBL ZR( buliding height) will not be used , only for some radiative and thermal right? num_urb_params = 132 represent which parameters?

sounds like too much questions, now I am studying in KIT alps as a PhD focus on WRF-urban in simulating China heat island and precipitation, I am a newcomer in this field. I see that your research group has a lot of experience in urbanization research. Can I apply for a visit and study with you for a period of time?
Looking forward to your response!
Vielen Danke!
Qi

**Comment by matthiasdemuzere** [comment]
Hi @sunqiccgk,

Thanks for your interest in our products.

To be honest, I am not 100% sure if I understand what you write about d02 and d03.

But in any case, you can apply `W2W` on both domains separately. I would eg. make two distinct folders `d02` and `d03`, each containing the `LCZ tif` and the corresponding `geo_em` file.

Then you can apply `W2W` twice:

```console
> w2w d02/ LCZ.tif geo_em.d02.nc
> w2w d03/ LCZ.tif geo_em.d03.nc
```

For each of the domains, the LCZ information will then be ingested, as described in the JOSS paper.
If you do not ingest the LCZ information (e.g. for domain d01), then the default URBPARM table will be used.

For your last question:
- Most of the morphological parameters are based on the new `LCZ_UCP_default.csv` table. In case these values are not appropriate for your area of interest, you can always change them, as described in the README. So you are correct that building height ZR is **not** sourced from [URBPARM_LCZ.TBL](https://github.com/wrf-model/WRF/blob/master/run/URBPARM_LCZ.TBL), but from [LCZ_UCP_default.csv](https://github.com/matthiasdemuzere/w2w/blob/main/w2w/resources/LCZ_UCP_lookup.csv)
- Other parameters (radiative, thermal, ...) are assigned to the model LCZ class embedded within the LU_INDEX, and are sourced from `URBPARM_LCZ.TBL`.
- the parameter numbers as available in the 3D URB_PARAMS matrix are explained [here, Table 1](https://ral.ucar.edu/sites/default/files/public/product-tool/NUDAPT_44_Documentation.pdf).

In case you are interested in a research visit, I suggest you to write an email to our team lead, [Prof. Dr. Benjamin Bechtel](https://www.climate.ruhr-uni-bochum.de/team/benjamin-bechtel/).

I hope this helps.

**Comment by sunqiccgk** [comment]
Hi @matthiasdemuzere ,thanks  a lot for you response.
The reason why I raised Q1-Q3,  the tiff file I had was so small to cover d02, so I design d03 to incorporate the derived LCZ information into d02, only use d03 is small too because it is recommended to have domains no smaller than about 100x100 if I set d02 and d03(90 x 89) in at least 1 km resolution to avoid the grey zone problem.
So do you have any recommended solutions for this problem?

**Comment by sunqiccgk** [comment]
For the parent domain, the value of LU_INDEX is not changed from 1-21 to 1-41, right?

**Comment by matthiasdemuzere** [comment]
> The reason why I raised Q1-Q3, the tiff file I had was so small to cover d02, so I design d03 to incorporate the derived LCZ information into d02, only use d03 is small too because it is recommended to have domains no smaller than about 100x100 if I set d02 and d03(90 x 89) in at least 1 km resolution to avoid the grey zone problem.
So do you have any recommended solutions for this problem?

Do I understand it well you are looking for a larger LCZ map that covers your d02 domain? If that is the case, and you want to use the LCZ Generator, you should make sure that your training area polygons in your training area file cover your whole domain of interest. The LCZ Generator automatically takes a bounding box around the out polygons, with a buffer on all sides of 10 km (see section 2.1 in [Demuzere et al., 2021](https://www.frontiersin.org/articles/10.3389/fenvs.2021.637455/full)).

In case your area then exceeds the 2.5° by 2.5° domain area threshold, you can reach out to lcz-generator [at] rub.de, and we can process this manually.

> Can I use the global dataset mentioned in the website (Demuzere, M., Kittner, J., Martilli, A., Mills, G., Moede, C., Stewart, I. D., van Vliet, J., and Bechtel, B.: A global map of Local Climate Zones to support earth system modelling and urban scale environmental science, Earth Syst. Sci. Data Discuss. [preprint], https://doi.org/10.5194/essd-2022-92, in review, 2022) to do a small regional or city research?

Of course. Paper is still under review, but the dataset is already publicly available. See Zenodo link in abstract of the paper.

**Comment by matthiasdemuzere** [comment]
> For the parent domain, the value of LU_INDEX is not changed from 1-21 to 1-41, right?

With parent domain you mean d01?
If so, the values of LU_INDEX are indeed **_not_** changed to the LCZ-based classes.

Yet if you use `W2W`, you should also provide all parent domains in your input folder. As `W2W` does change some of the global attributes to make it work in the WRF/WPS system. See [Step 5 in the JOSS paper (under review)](https://github.com/matthiasdemuzere/w2w/blob/main/JOSS/paper.pdf).

**Comment by sunqiccgk** [comment]
> Thanks a lot for your response, I download the global data, and use small part of them for my inner domain d03, for the d01 and d02 only the global attribute is changed. WRF uses d01_41.nc and d02_41.nc, when they have urban land use type ( LU_index 13), they still use old TBL, not LCZ.TBL, right?

> By the way, if d03 both have LU_index 13 and LU_index 31-40, which TBL WRF will use? 

> I compare the global data (first one ) with wudapt upload data in same region, I noticed there are some differences in LU_index distribution, according to your experience, do you think the impact of this difference is huge or small in precipitation?

Thanks for your patience:).
Qi
![wrf_station_piexl_lu_index_ori_d02_41](https://user-images.githubusercontent.com/99535285/178474820-7b267a6b-e7fd-40e7-a0e1-e6708c1f99d9.png)
<img width="285" alt="image" src="https://user-images.githubusercontent.com/99535285/178474973-a74b404f-501a-48ca-a3dc-1f2e0d9684ca.png">

**Comment by matthiasdemuzere** [comment]
> Thanks a lot for your response, I download the global data, and use small part of them for my inner domain d03, for the d01 and d02 only the global attribute is changed. WRF uses d01_41.nc and d02_41.nc, when they have urban land use type ( LU_index 13), they still use old TBL, not LCZ.TBL, right?

Indeed. Whether or not the LCZ-based urban canopy parameters are used is defined by `use_wudapt_lcz`, which should be `1` in case you want to use the LCZ information. See `important notes` in the [JOSS paper](https://github.com/matthiasdemuzere/w2w/blob/main/JOSS/paper.pdf)

> By the way, if d03 both have LU_index 13 and LU_index 31-40, which TBL WRF will use?

The geo_em.d0X file should **_never_** contain LU_INDEX 13 and 31-41 simultaneously. That is because we integrate the LCZ extent and values in the geo_em.d0X_NoUrban.nc file, which has no urban pixels.

> I compare the global data (first one ) with wudapt upload data in same region, I noticed there are some differences in LU_index distribution, according to your experience, do you think the impact of this difference is huge or small in precipitation?

I am afraid I can not answer this. Depends on e.g. the extent of differences between the 2 LCZ maps, in which LCZ classes these difference occur (some LCZ classes have very similar urban parameters), the background climate and the sensitivity of precipitation on the underlying urban form.

As a rule of thumb: if you believe the global LCZ map is representative for your city of choice, you can use that map. If you think the map deviates too much from reality, then it makes sense to make a city-specific map using the LCZ Generator. The latter of course requires you to digitize training areas, for which you can find detailed guidelines [here](https://www.wudapt.org/digitize-training-areas/).

**Comment by sunqiccgk** [comment]
yes, I read all the information in JOSS paper and when in namelist.input use_wudapt_lcz= 1 and num_lat_cat =41 , d03_para.nc data LCZ.TBL will be used. I just want to make sure d02_41 and d01_41 use this or not.

According to JOSS paper, I notice the urban land use is removed already, but because I incorporate d03 information into d02 so there is still 13 index in d02.
If my domain is not big enough, It is better to use a larger domain rather than incorporating small domain(d03) information into the bigger domain(d02), right?
Thanks a lot! 👍

**Comment by matthiasdemuzere** [comment]
Yes, I would really not introduce d03 information into d02.

Just make sure your LCZ map is large enough to cover the d02 domain, and then you can apply `W2W` on d02 directly.
