### ISSUE TITLE
wrfinput file problem-Urban morphological parameters

### ISSUE THREAD

**Issue by sunqiccgk** [matthiasdemuzere/w2w#79]
Hi, professor. 
I check the geo_em.d02.nc and find a new variable named urban_parameter, but in the wrfinput_d02(inner domain) file and I just find BUILD_AREA_FRACTON, BUILD_HEIGHT, BUILD_SURF_RATIO, MH_URB2D, STDH_URB2D and LF_URB2D six valid and related variables when using LCZ map and Single layer scheme and BUILD_AREA_FRACTON, BUILD_HEIGHT, BUILD_SURF_RATIO and HEIGHT_HISTOGRAMS in Multi-layer scheme. 
Is the result correct or not?  Because in the JOSS file, you mentioned some width variables such as SW and HW. only radiative and thermal parameters are used TBL file.

Secondly, do you have some documentation on how these variables used in the WRF-Urban procedure?

Looking forward to your response!
Cheers,
Qi
![image](https://user-images.githubusercontent.com/99535285/180465056-2f33f0f6-7ab2-49f9-b4fa-93426b5cd9d1.png)

![image](https://user-images.githubusercontent.com/99535285/180464533-4ac63bad-0de3-4a90-b1eb-877ed37289f7.png)

**Comment by dargueso** [comment]
Dear Qi, 
I'm not sure I understand your 1st question and not sure either how it relates to the screenshot you attach. 

As for how WRF handles the urban parameters, it depends on which urban option you're using. You're best option is to read the original papers for your particular scheme. Which one are you planning to use? Single-layer?

**Comment by sunqiccgk** [comment]
Dear dargueso,
the first screenshot is to show the variables in the wrfinput_d02 file. the second screenshot is about some urban parameters you mentioned in the paper I didn't find in the wrfinput_d02 file (red rectangle).
I plan to evaluate  the simulation results from different UCMs.

**Comment by dargueso** [comment]
Ok, I see. 
If you plan to evaluate different UCMs, I recommend you to read their respective documentation to understand how the parameters are ingested and treated (i.e., Kusaka et al. 2001, Martilli et al. 2002, Salamanca et al. 2010...).

I think your outputs are correct because the variables mentioned in the JOSS paper are intermediate variables that replace those prescribed in the default TBL file. Those intermediate variables are used to generate information for the different categories, as far as I know. Perhaps @matthiasdemuzere and @andreazonato can confirm this.

**Comment by andreazonato** [comment]
Hi Qi,

Actually, BW SW and building height information are stored in the lampda_p and lambda_f, so they are not necessary to be explicit in the wrfinput file.
Regarding the documentation, I suggest as @dargueso said, to look at the paper mentioned there (check even mine, Zonato,2020, where I derive the various lambda from BW and SW).


Cheers

Andrea

**Comment by sunqiccgk** [comment]
Hi Andrea and Dargueso,
Thanks for your response!  I read your paper Zonato,2020 yesterday and it is quite interesting. But I am still wondering where is lampda_p and lambda_f stored to give the equation's input in UCMs.

Cheers,
Qi

**Comment by andreazonato** [comment]
@sunqiccgk, the variables in WRFINPUT for the urban part are build_area_fraction and  build_surf_ratio

Andrea

**Comment by sunqiccgk** [comment]
plus, What does w stand for in this formula? in Zonato,2020
![921658826644_ pic](https://user-images.githubusercontent.com/99535285/180970152-46b032a8-42ce-42c1-ad7b-89a960f1ce26.jpg)

**Comment by sunqiccgk** [comment]
and in NUDAPT 44 Documentation Table 1 mentioned a lot of variables, but in wrfinput only had variables not in black color in the table, how about the black variables, they are useful or not in UCMs? and I found in wrfinput file a variable named BUILD_HEIGHT and a variable named MH_HEIGHT,  I am wondering the difference between them.  One more question, if I use default landuse data from MODIS, the urban has only one class, but when I check the URBPARM.TBL, there is three classes, do u know how they classify cities？ through FRC_URB2D？ I check this variable value is constant and equal to 0.90 in the wrfinput file using MODIS data. @andreazonato 

Thank you very much!
Cheers,
Qi

**Comment by andreazonato** [comment]
> plus, What does w stand for in this formula? in Zonato,2020 ![921658826644_ pic](https://user-images.githubusercontent.com/99535285/180970152-46b032a8-42ce-42c1-ad7b-89a960f1ce26.jpg)

the street witdth, or the distance between buildings!



> and in NUDAPT 44 Documentation Table 1 mentioned a lot of variables, but in wrfinput only had variables not in black color in the table, how about the black variables, they are useful or not in UCMs? and I found in wrfinput file a variable named BUILD_HEIGHT and a variable named MH_HEIGHT, I am wondering the difference between them. One more question, if I use default landuse data from MODIS, the urban has only one class, but when I check the URBPARM.TBL, there is three classes, do u know how they classify cities？ through FRC_URB2D？ I check this variable value is constant and equal to 0.90 in the wrfinput file using MODIS data. @andreazonato

The wrfinput gives you only the variable necessary for your UCM, so if you use BEP+BEM you are gonna have BUILD_HEIGHT, while if you use SLUCM you are gonna have MH_HEIGHT. Regarding the landuse, it is not made for urban simulations. In order to have 3 or more classes you have to modify it

**Comment by sunqiccgk** [comment]
@andreazonato.  thanks for you response!
1. in your paper, S stand for street width and b stand for building width, so W have the same meaning with S right? 
2. according to NUDAPT table 1, URB_PARAM have 132 dimensions in geo_em.d02.nc, however, only purple variables still stored in the wrfinput file, so other variable such as Fontal area density useless in UCM, right?
3. if I use default MODIS land use data in WRF and BEP scheme. in URBPARM.TBL has three categories, so which categories the urban land type belong to?   This decide which urban parameters will be used later in equation. or directly use this landuse data is not right, do u know how to modify it into three categories?

Cheers,
Qi

**Comment by andreazonato** [comment]
> * in your paper, S stand for street width and b stand for building width, so W have the same meaning with S right?

Exactly! That's a mistake in the paper




> 2\. according to NUDAPT table 1, URB_PARAM have 132 dimensions in geo_em.d02.nc, however, only purple variables still stored in the wrfinput file, so other variable such as Fontal area density useless in UCM, right?

For BEP+BEM they are not. Regarding SLUCM, I have no idea, I'm not used to that UCM. You should ask to whom developed that model



> 3\. f I use default MODIS land use data in WRF and BEP scheme. in URBPARM.TBL has three categories, so which categories the urban land type belong to?   This decide which urban parameters will be used later in equation. or directly use this landuse data is not right, do u know how to modify it into three categories?

If you use MODIS, I think it assigns automatically the urban landuse to class 32.  
I don't know how to  set it to 3 categories. However, you can use the tool Matthias, Daniel and me developed to extend it to 10 WUDAPT categories.


Andrea
