### ISSUE TITLE
domain problem

### ISSUE THREAD

**Issue by fipoucat** [matthiasdemuzere/w2w#87]
I facing error with my domain to se with my lcz file, what to do to correct this?
--> Set data, arguments and files 
> Using layer 0 of the LCZ GeoTIFF. Can be changed with -l (--lcz-band)
--> Check LCZ integrity, in terms of class labels, projection and extent
> LCZ labels as expected (1 to 17)
> LCZ provided as WGS84 (EPSG:4326)
ERROR: LCZ domain should be larger than WRF domain in all directions.
LCZ bounds (xmin, ymin, xmax, ymax): (-17.7210656098258, 13.83764863657711, -16.1840481586973, 15.46988750782228)
WRF bounds (xmin, ymin, xmax, ymax): (-17.990726470947266, 13.280853271484375, -15.958621978759766, 15.464736938476562)

**Comment by dargueso** [comment]
It looks like your domain is larger than the area covered by the LCZ image. 

`ERROR: LCZ domain should be larger than WRF domain in all directions.`

Please, try to use a larger LCZ and see if that solves the problem.

**Comment by fipoucat** [comment]
I ll try to adjust the wrf domain because creating lcz for Africa cities is complicated

**Comment by fipoucat** [comment]
Hi Mathias, thank you for the nice work. The file (lcz) I was trying is the one you gave me during BUCS2018 for Dakar. 
I'll look at the global map and will see how to extract a domain that fits the wrf one.

**Comment by fipoucat** [comment]
I don't understand why lcz domain should be larger than the wrf domain, not in the sample data if I understand well

**Comment by fipoucat** [comment]
after another extraction I am getting a different error:

Dataset has no geotransform, gcps, or rpcs. The identity matrix will be returned

**Comment by matthiasdemuzere** [comment]
> I don't understand why lcz domain should be larger than the wrf domain, not in the sample data if I understand well

The LCZ map is being regridded / resampled to the WRF domain and its resolution. For that to work it is essential that both the LCZ and WRF domains overlap, to make sure the information is complete.

**Comment by matthiasdemuzere** [comment]
> Dataset has no geotransform, gcps, or rpcs. The identity matrix will be returned

Your issue might be related to [this one](https://github.com/matthiasdemuzere/w2w/issues/63). This was solved by using a clean python environment before installing / running the `W2W` tool.

For future issues: please provide a more complete bug report, as explained [here](https://github.com/matthiasdemuzere/w2w/issues/63). Otherwise we just have to guess what is happening.

**Comment by fipoucat** [comment]
OK, that make sense, and issue is solved using the link guidance
