### ISSUE TITLE
Failed to input to metgrid.exe

### ISSUE THREAD

**Issue by StrayMetal** [matthiasdemuzere/w2w#88]
Thanks for the great work!

I am encountering an error when I try to run the metgrid.exe using the inner domain nc file adjusted by the w2w tool. The error from metgrid.exe is,

Processing domain 1 of 3
ERROR: Couldn't open file ./geo_em.d01.nc for input.
Abort(22030) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 22030) - process 0

The geo_em.d01.nc is a renamed file from  geo_em.d01_41.nc.
I tried to degrade the WRF to version 4.3 and WPS to 4.3, which still failed.
Is there any method to solve this problem?
Thanks a lot for your reading!

**Comment by matthiasdemuzere** [comment]
This seems to be related to #9 (and issues mentioned in there)?

Reason for error: WRF/WPS not compiled with netcdf$/hdf5 enabled. 
So please check linked issue and try to address accordingly.

**Comment by StrayMetal** [comment]
> This seems to be related to #9 (and issues mentioned in there)?
> 
> Reason for error: WRF/WPS not compiled with netcdf$/hdf5 enabled. So please check linked issue and try to address accordingly.

Thank you very much for your reply!
I rebuild the netcdf with hdf5 and then rebuild the WRF. And it works!

**Comment by matthiasdemuzere** [comment]
Glad to see this works for you now!
