### ISSUE TITLE
Couldn't open ./geo_em.d02.nc for input

### ISSUE THREAD

**Issue by NicMan89** [matthiasdemuzere/w2w#9]
The metgrid.exe provide me the following error message:

ERROR: Couldn't open ./geo_em.d02.nc for input
Note: The following floating-point exceptions are signalling: IEE_OVERFLOW_FLAG IEE_UNDERFLOW_FLAG IEE_DENORMAL

With w2w tool and EU_LCZ_map_epsg4326.tif (from https://figshare.com/articles/dataset/European_LCZ_map/13322450), I got the 3 output files from w2w.py  
I have copy and paste the geo_em.d02_LCZ_params.nc and rename it to the standard name geo_em.d02.nc. 
I don't understand where is the mistake, I tried to use the new geogrid output from w2w for only d02 domain and for d01 and d02 domains but the error message is always the same. I use WPS 3.9.0.1 version.

Thank you in advance for your precious time.

**Comment by matthiasdemuzere** [comment]
1. Are you sure `geo_em.d02.nc` is in the folder that metgrid.exe expects it to be?

2. This issue might be similar to one: #2. The problem there was that WRF is not compiled with the netcdf/hdf5 libraries that are used to create the LCZ-based geo_em files. You could check this by testing: 

```> ncdump geo_em.d02.nc``` on the lcz-based geo_em file.

See [here](https://github.com/matthiasdemuzere/w2w/issues/2#issuecomment-868375591).

If that is the problem, you should probably first recompile netcdf4 (enabling hdf5), and then re-compile WRF.

Please let us know how this works for you ...
