### ISSUE TITLE
question

### ISSUE THREAD

**Issue by fipoucat** [matthiasdemuzere/w2w#91]
Which file should I use from the available city lcz downloaded from the global map in w2w?

Thank you

**Comment by matthiasdemuzere** [comment]
@fipoucat: sorry, I do not understand your question. Could you be more clear / specific?

**Comment by fipoucat** [comment]
I downloaded a city the lcz is already generated and in the folder, there is an image named lcz_map.jpg in the figures subfolder and another with .tif but all seem to have 3 bands and wonder which one to use for the different lcz classes.

**Comment by theendlessriver13** [comment]
I also (still) have a hard time following you...
Are you referring to the lcz generator maps (https://lcz-generator.rub.de/submissions) or the global map (https://zenodo.org/record/6364594)?
For the former you can specify the band using the `--lcz-band` argument as described here (https://github.com/matthiasdemuzere/w2w#important-notes)
The different bands are described in the lcz generator paper (https://doi.org/10.3389/fenvs.2021.637455) or result email. The first band is the raw lcz map, the second one the filtered version and the third one the class probability.
For the latter, the global map you want to crop out your ROI first before running `w2w`.

**Comment by fipoucat** [comment]
Sorry Dakar for the confusion, I am referring to the submissions lcz. This one looks "more accurate" than the one I extracted from the global map. I was facing the band and crs of the image from the submission for Dakar city.

**Comment by theendlessriver13** [comment]
So is this resolved now? Or do you have other questions?

**Comment by fipoucat** [comment]
Yes, thank you
